#!/usr/bin/env bash
# ==============================================================================
# Example Music Limited — Ansible Node Bootstrap Script
# EXAANSCLD001 (or any site's ansible/management node)
#
# Mirrors the style of firewallme.sh:
#   - Interactive, idempotent, run as root
#   - Site-code-driven (subnet/inventory auto-derived)
#   - Self-bootstraps all dependencies
#   - Generates SSH keypair for ansible user
#   - Downloads exa_pretty.py callback from GitHub
#   - Writes ansible.cfg, inventory, group_vars scaffolding
#   - Fixes known first-run issues (sudoers path, etc.)
#   - Onboards PVE nodes via pve_onboard.yml
#   - Tests connectivity with ansible ping
#   - Sentinel file + dynamic MOTD
#
# NOTE: Playbooks are NOT generated by this script. They live in the
#       Example Music GitHub repo. Section 5 clones the repo automatically
#       into /home/ansible/example-music-infra and symlinks the ansible/
#       subfolder to /home/ansible/ansible using full paths. On re-runs
#       the existing clone is pulled (--ff-only) rather than re-cloned.
#
# -------------------------------------------------------------------------------------------------
# Version history
# -------------------------------------------------------------------------------------------------
# v1.0.0  2025-??-??  Initial release
# v1.1.0  2025-??-??  Fix mkdir brace expansion fail inside double quotes; expand to explicit paths
#                     Fix apt hung on interactive prompts (libguestfs-tools kernel selection) or
#                     cause OOM by adding recommended pkgs; remove -qq add --force-confold/confdef,
#                     --no-install-recommends
# v1.2.0  2026-06-14  Fix: load_sites_csv() while-read loop dropped last CSV line when file had no
#                     trailing newline (read returns non-zero at EOF, loop exited before processing
#                     that iteration). VIE is the last line in sites.csv & has no trailing newline,
#                     so never loaded into  SITE_OCTET[]; "Unknown site code 'VIE'" at runtime. Fix
#                     with || [[ -n "$site" ]] on the while condition, warn() now writes to stderr
#                     (>&2) for consistency with firewallme.sh and to prevent future $() subshell
#                     captures picking up warning text as data.
# v1.3.0  2026-06-14  Quieten apt output: -qq + stdout to /dev/null on install line; errors still
#                     surface on stderr. Section 8 (additional managed hosts): smart CSV-fill mode.
#                     Recognises group names dc/dcs & firewalls/fw & offers to auto-build IPs from
#                     SITE_DC[]/SITE_FW[] loaded from sites.csv. Operator can select all sites or a
#                     subset by code. Falls back to manual for unrecognised group names or when CSV
#                     offer declined. PVE nodes explicitly excluded from smart-fill (kept as-is).
#                     SITE_DC and SITE_FW arrays added to load_sites_csv().
# v1.4.0  2026-06-14  Fix authorized_keys missing \n between entries. If file had no trailing \n,
#                     appended keys ran together on one line breaking both. Use printf & checks for
#                     trailing newline before appending.
#                     Fix inventory self-entry hostname -I (old/prov IP) instead of canonical .10
#                     management IP from SITE_DC[$SITE_CODE] in the CSV.
#                     Fix ansible.cfg stdout_callback updated to ansible.builtin.default (correct
#                     for ansible-core 2.19+; bare 'yaml' is a result_format value, not a callback
#                     name). Added result_format = yaml explicitly. StrictHostKeyChecking changed
#                     from 'no' to 'accept-new' accepts new host keys on first connect but rejects
#                     changed keys, which 'no' does not. Fix sudoers drop-in now validated (visudo
#                     -cf) & permissions enforced on this host directly, not only copied to files/
#                     for playbook distribution.
# v1.5.0  2026-06-15  Section 8 rewritten as infrastructure discovery. Choose: A) SSH subnet scan,
#                     B) CSV-only fill, or C) skip. Scan mode prompts for which subnets to cover:
#                     PROV (139), all site LANs via CSV, WireGuard tunnels (10.0.x.0/24), or custom.
#                     Each reachable host is classified by last octet (10/11 DCs, 253 FWLs, 48 PBX)
#                     & provisioning-net position (139.10 ANS). DNS PTR lookup labels each entry.
#                     Unknowns appear as a commented-out [unknowns] stanza in the inventory for
#                     operator review.  CSV-only mode pre-fills [dcs] & [firewalls] from SITE_DC[]/
#                     SITE_FW[] without scanning. Additional groups can be added manually after
#                     either mode. Inventory write updated to consume DISC_HOSTS_BY_GROUP.
# v1.6.0  2026-06-16  Fix ansible listed twice in BOOTSTRAP_PKGS, once via early command -v check &
#                     again in Debian version block. On fresh install apt downloads twice, causing
#                     OOM pressure. Removed early unconditional check; version block handles it.
#                     Fix apt install redirected to /dev/null so OOM kills were completely silent
#                     (just "Killed" with no context). Now logs to a mktemp file; on failure prints
#                     last 20 lines & preserves the log for inspection. Fix: memory check added
#                     before apt install; warns if less than 512MB available as ansible unpacked
#                     needs ~400MB and the OOM killer hits silently below that.
# v1.7.0  2026-06-16  Section 7 rewritten: PVE nodes auto-populated from CSV at .5 (primary) and .6
#                     (secondary) for all sites. Operator only prompted for additional nodes not in
#                     CSV. CSV-only mode deduplicates entries by IP so BRD/BER (both 192.168.113.x)
#                     produce one merged comment not duplicates. All inventory IP entries padded to
#                     15 chars before # for consistent column alignment (max IPv4 is 15 chars).
#                     CSV-only success message now lists all groups built ansiblehosts, pvenodes,
#                     dcs, firewalls. [pvenodes] always written to inventory; entries pre-populated
#                     from CSV are always present.
# v1.8.0  2026-06-16  ansible.cfg updated to match hand-crafted version: host_key_checking = True
#                     (was False — accept-new handles new hosts; True catches changed fingerprints
#                     correctly). Added forks = 50, timeout = 5, connect_timeout = 5. Added
#                     [persistent_connection] section (command_timeout=30, connect_retry_timeout=15).
#                     Full inline comment blocks & recommended playbook settings added to config.
# v1.9.0  2026-06-17  Fix "Host key verification failed" on first ansible run against IPs reused
#                     from a previous build (e.g. this very ansible node rebuilding at the same
#                     provisioning IP).
#                     accept-new correctly REJECTS changed host key as a MITM safeguard — but stale
#                     fingerprint from a node's prior incarnation triggered exactly that rejection
#                     on healthy hosts, with no clear cause in the error message. Section 7B clears
#                     known_hosts entries (both the ansible user's own & /etc/ssh/ssh_known_hosts)
#                     for every CSV-derived IP (.5/.6/.10/.253 per site) plus, this node's own prov
#                     IP BEFORE discovery scan runs, so scan isn't confused by stale fingerprints.
#                     Add section 10B: final catch-all pass over actual written inventory, covering
#                     custom subnets/manually added groups that a CSV-only sweep would not "see".
#                     Both passes use ssh-keygen -R (idempotent, silent if no entry exists) accept-
#                     new then trusts the current key on next connect with no security regression.
# v1.10.0 2026-06-17  Section 6 (SSH keypair) now offers a choice: generate a new keypair on host
#                     (unchanged default), or paste an existing PUBLIC key only. Private keys are
#                     never accepted via paste — pasting a private key into a terminal/script means
#                     it travelled through clipboard & shell history, which we will not do. Paste
#                     mode writes only ansible-id_rsa.pub & prints an orange-bordered warning box
#                     with the exact path the matching private key must be copied to (scp example
#                     included), plus chown/chmod instructions. A second reminder appears at the
#                     end of the run if the private key still isn't present, & section 8 (discovery
#                     scan) now warns up front that the SSH scan will fail every host until the key
#                     is placed. Fix missing space in the final banner pve_onboard.yml command.
# v1.11.0 2026-06-18  Section 1b added: static IP configuration transplanted
#                     from bindme.sh. Detects provisioning interface, checks
#                     target IP is free (ping + arping), pins interface name via
#                     systemd .link, strips ifupdown stanzas, fixes NM managed=
#                     false, removes stale profiles, writes ansible-static NM
#                     profile with autoconnect yes + priority 100. NM restart
#                     deferred (same SSH-safety fix as firewallme.sh). ip_in_use()
#                     helper added. arping and network-manager added to BOOTSTRAP_PKGS.
#                     Section 1c added: hostname prompt matching bindme.sh pattern.
#                     Detects EXA* convention hostname, normalises to uppercase,
#                     defaults to EXAANSCLD001 if convention not matched. Sets
#                     hostname via hostnamectl and adds /etc/hosts entry.
# v1.12.0 2026-06-25  configs/inventory is now a directory, not a flat file. Ansible merges all
#                     .ini files in the directory automatically, so per-site and per-service
#                     inventory files (cld.ini, kge.ini, fal.ini, rudder.ini, etc.) can live
#                     alongside the generated main.ini without polluting it. INVENTORY_FILE now
#                     points to configs/inventory/main.ini (the generated file); ansible.cfg and
#                     all ansible commands reference configs/inventory (the directory). Section 10b
#                     now greps all *.ini files in the directory instead of just main.ini.
#                     group_vars/firewalls/main.yml added for WireGuard hub reference data.
# v1.13.0 2026-06-26  Section 5b added: data file bootstrap. devices.csv and sites.csv are
#                     canonical at /etc/example-music/ (placed by preseed late_command).
#                     Script now checks for both and downloads from the provisioning server
#                     (VRACK_NET.50/proxmox/) if either is missing. devices.csv is also
#                     copied to ansible/files/ for the bind9-dns.yml playbook. bind9-dns.yml
#                     devices_csv_path default updated to /etc/example-music/devices.csv.
# v1.14.0 2026-06-27  Major overhaul based on real-world testing:
#                     - Playbook generation (section 12) removed. Playbooks live in GitHub.
#                       Script now prints a reminder to clone the repo.
#                     - ansible.cfg generation updated: exa_pretty callback added (downloaded
#                       from GitHub), become=False (global become disabled — Linux hosts get
#                       it via group_vars/linux/, Windows hosts correctly get no become),
#                       display_skipped_hosts, display_failed_stderr, [callback_exa_pretty]
#                       section all added to match battle-tested hand-crafted config.
#                     - exa_pretty.py downloaded from GitHub into callback_plugins/ instead
#                       of being written inline.
#                     - group_vars/all/main.yml: ansible_become removed (now in
#                       group_vars/linux/main.yml only, preventing sudo on Windows hosts).
#                     - group_vars/linux/main.yml added: become=true/sudo for all Linux groups.
#                     - Directory scaffold expanded to match full repo structure including
#                       group_vars/linux, group_vars/windows_nodes, group_vars/windows,
#                       group_vars/windows_server, group_vars/windows_desktop,
#                       group_vars/windows_laptop, group_vars/windows_dc, group_vars/firewalls,
#                       group_vars/rudder_servers, group_vars/rudder_relays, callback_plugins/,
#                       handlers/, vars/, and all playbook subdirectories.
#                     - PROV_NET renamed to VRACK_NET throughout for clarity (192.168.139.x
#                       is the vRACK/bootstrap network, not the CLD site LAN which is 69.x).
#                       VRACK_SERVER set to VRACK_NET.50 (bootstrap web server).
#                     - CLD site: EXAANSCLD001 correctly placed at 192.168.69.9, not 139.x.
#                     - [linux:children] group added to main.ini covering managed, rudder_servers,
#                       rudder_relays, ansiblehosts so group_vars/linux/ applies correctly.
# v1.15.0 2026-06-30  Section 5 rewritten: git clone replaces mkdir -p directory scaffold.
#                     Clones https://github.com/knightmare2600/example-music-infra into
#                     /home/ansible/example-music-infra then symlinks the ansible/ subfolder
#                     to /home/ansible/ansible using full paths. Re-run safe: existing clone
#                     skips re-clone and does git pull --ff-only instead; existing symlink is
#                     kept as-is (real dir blocks with a warning). Runtime-only dirs that are
#                     not in the repo (configs/inventory, callback_plugins, group_vars/*) are
#                     still created with mkdir -p. Existence guards added to all cat > file
#                     writes (ansible.cfg, inventory, group_vars/*) so re-runs do not
#                     overwrite operator-edited files.
#
# ==============================================================================

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

# ------------------------------------------------------------------------------
# Colour helpers  (identical to firewallme.sh)
# ------------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; WHITE='\033[1;37m'; NC='\033[0m'
info()    { echo -e "${CYAN}[*]${NC} $*"; }
success() { echo -e "${GREEN}[+]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*" >&2; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
section() { echo; echo -e "${WHITE}── $* ──${NC}"; echo; }

# Checks whether an IP is already live on the network (ping + arping fallback)
ip_in_use() {
  local ip="$1"
  if ping -c1 -W1 "$ip" &>/dev/null 2>&1; then
    return 0
  fi
  if command -v arping &>/dev/null; then
    local gw_iface
    gw_iface=$(ip route | awk '/default/{print $5}' | head -1)
    if [[ -n "${gw_iface}" ]] && arping -c1 -W1 -I "$gw_iface" "$ip" &>/dev/null 2>&1; then
      return 0
    fi
  fi
  return 1
}

# ------------------------------------------------------------------------------
# Must run as root
# ------------------------------------------------------------------------------
[[ $EUID -ne 0 ]] && die "Run this script with sudo or as root."

# ------------------------------------------------------------------------------
# Site data -- loaded from sites.csv (single source of truth)
# To add or change a site, edit sites.csv -- no code changes needed.
#
# Looks for sites.csv in:
#   1. $SITES_CSV environment variable (override)
#   2. Same directory as this script
#   3. /etc/example-music/sites.csv (system-wide install)
# ------------------------------------------------------------------------------
declare -A SITE_OCTET SITE_CITY SITE_COUNTRY SITE_ENTITY SITE_DC SITE_FW

load_sites_csv() {
  local csv_path=""

  if [[ -n "${SITES_CSV:-}" && -f "${SITES_CSV}" ]]; then
    csv_path="${SITES_CSV}"
  else
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if [[ -f "${script_dir}/sites.csv" ]]; then
      csv_path="${script_dir}/sites.csv"
    elif [[ -f "/etc/example-music/sites.csv" ]]; then
      csv_path="/etc/example-music/sites.csv"
    fi
  fi

  if [[ -z "${csv_path}" ]]; then
    echo -e "\033[0;31m[ERROR]\033[0m sites.csv not found." >&2
    echo -e "  Looked in: same directory as script, /etc/example-music/sites.csv" >&2
    echo -e "  Set SITES_CSV=/path/to/sites.csv to override." >&2
    exit 1
  fi

  local first=1
  # BUG FIX: `while read` silently drops the last line of a file with no trailing
  # newline — read returns non-zero at EOF so the loop exits without processing
  # that final iteration.  sites.csv has no trailing newline; VIE is the last
  # entry and was therefore never loaded.  The || [[ -n "$site" ]] guard catches
  # the partial read and processes it normally.
  while IFS=',' read -r site city country cc subnet gateway dc fw landline mobile tz ansible_region entity _rest \
      || [[ -n "$site" ]]; do
    [[ "${first}" -eq 1 ]] && { first=0; continue; }   # skip header row
    site="${site// /}"
    [[ -z "${site}" ]] && continue
    local octet
    octet=$(echo "${subnet}" | awk -F'.' '{print $3}')
    SITE_OCTET["${site}"]="${octet}"
    SITE_CITY["${site}"]="${city}"
    SITE_COUNTRY["${site}"]="${country}"
    SITE_ENTITY["${site}"]="${entity}"
    SITE_DC["${site}"]="${dc}"
    SITE_FW["${site}"]="${fw}"
  done < "${csv_path}"
}

load_sites_csv

# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------
ANSIBLE_USER="ansible"
ANSIBLE_HOME="/home/ansible"
ANSIBLE_DIR="${ANSIBLE_HOME}/ansible"
CONFIGS_DIR="${ANSIBLE_DIR}/configs"
PLAYBOOKS_DIR="${ANSIBLE_DIR}/playbooks"
FILES_DIR="${ANSIBLE_DIR}/files"
CALLBACK_DIR="${ANSIBLE_DIR}/callback_plugins"
KEY_FILE="${CONFIGS_DIR}/ansible-id_rsa"
KEY_PUB="${CONFIGS_DIR}/ansible-id_rsa.pub"
INVENTORY_FILE="${CONFIGS_DIR}/inventory/main.ini"
ANSIBLE_CFG="${ANSIBLE_DIR}/ansible.cfg"
NODEINFO="/etc/example-music/nodeinfo.json"

# vRACK — the OVH provisioning/bootstrap network (192.168.139.0/24)
# This is NOT the CLD site LAN (192.168.69.0/24).
# The bootstrap web server lives at VRACK_NET.50.
VRACK_NET_DEFAULT="192.168.139"
VRACK_GW_DEFAULT="254"   # vRACK gateway is .254

# GitHub raw URL for exa_pretty callback
EXA_PRETTY_URL="https://raw.githubusercontent.com/knightmare2600/example_music_infra/refs/heads/main/ansible/callback_plugins/exa_pretty.py"

# ------------------------------------------------------------------------------
# Banner
# ------------------------------------------------------------------------------
echo
echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║            Example Music:- Ansible Node Bootstrap            ║${NC}"
echo -e "${CYAN}║                         ansibleme.sh                         ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo
echo -e "${YELLOW}  Running on hostname: ${GREEN}$(hostname)${NC}"
echo

# ------------------------------------------------------------------------------
# 1. Bootstrap packages
# ------------------------------------------------------------------------------
section "1. Installing dependencies"
info "Updating package lists..."
apt-get update -qq 2>&1 | grep -E "^(Err|W:|E:)" || true

BOOTSTRAP_PKGS=()
# ansible is handled separately below (version strategy varies by Debian release)
command -v git          &>/dev/null || BOOTSTRAP_PKGS+=(git)
command -v ssh          &>/dev/null || BOOTSTRAP_PKGS+=(openssh-client)
command -v sshpass      &>/dev/null || BOOTSTRAP_PKGS+=(sshpass)
command -v python3      &>/dev/null || BOOTSTRAP_PKGS+=(python3)
command -v pip3         &>/dev/null || BOOTSTRAP_PKGS+=(python3-pip)
command -v curl         &>/dev/null || BOOTSTRAP_PKGS+=(curl)
command -v wget         &>/dev/null || BOOTSTRAP_PKGS+=(wget)
command -v vim          &>/dev/null || BOOTSTRAP_PKGS+=(vim)
command -v tmux         &>/dev/null || BOOTSTRAP_PKGS+=(tmux)
command -v tree         &>/dev/null || BOOTSTRAP_PKGS+=(tree)
command -v grc          &>/dev/null || BOOTSTRAP_PKGS+=(grc)
command -v zsh          &>/dev/null || BOOTSTRAP_PKGS+=(zsh)
command -v yamllint     &>/dev/null || BOOTSTRAP_PKGS+=(yamllint)
command -v gpg          &>/dev/null || BOOTSTRAP_PKGS+=(gpg)
command -v arping       &>/dev/null || BOOTSTRAP_PKGS+=(arping)
command -v nmcli        &>/dev/null || BOOTSTRAP_PKGS+=(network-manager)
# Python libs for Proxmox API and virt tools
dpkg -s python3-proxmoxer  &>/dev/null || BOOTSTRAP_PKGS+=(python3-proxmoxer)
dpkg -s python3-requests    &>/dev/null || BOOTSTRAP_PKGS+=(python3-requests)
dpkg -s python3-virtualenv  &>/dev/null || BOOTSTRAP_PKGS+=(python3-virtualenv)
command -v jq               &>/dev/null || BOOTSTRAP_PKGS+=(jq)

# NB: libguestfs-tools is intentionally NOT installed on the ansible node. It is
# only needed on PVE nodes, and is deployed there via the pve_onboard.yml and
# cloud_templates.yml playbooks. Installing here pulls in the full qemu/kvm pkgs
# (100s of MB, kernel images) which can cause OOM on small nodes.

# Ansible package strategy:
#   Debian 13 (trixie) — ships ansible 12.0.0 / ansible-core 2.19 in main repo. No PPA needed.
#   Debian 12 (bookworm) — ships ansible-core 2.14 which is too old; add Ubuntu jammy PPA.
#   Anything else — attempt main repo; warn if version is old.
DEBIAN_VERSION=$(. /etc/os-release && echo "${VERSION_ID:-0}")

if [[ "$DEBIAN_VERSION" -ge 13 ]] 2>/dev/null; then
  info "Debian ${DEBIAN_VERSION} (trixie+): ansible available in main repo — no PPA needed."
  BOOTSTRAP_PKGS+=(ansible)
elif [[ "$DEBIAN_VERSION" == "12" ]]; then
  info "Debian 12 (bookworm): adding Ubuntu jammy PPA for a current ansible version..."
  if [[ ! -f /usr/share/keyrings/ansible-archive-keyring.gpg ]]; then
    wget -q -O /tmp/ansible.gpg "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367"
    gpg --dearmour -o /usr/share/keyrings/ansible-archive-keyring.gpg /tmp/ansible.gpg
    rm -f /tmp/ansible.gpg
  fi
  if [[ ! -f /etc/apt/sources.list.d/ansible.list ]]; then
    echo "deb [signed-by=/usr/share/keyrings/ansible-archive-keyring.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu jammy main" > /etc/apt/sources.list.d/ansible.list
    apt-get update -qq 2>&1 | grep -E "^(Err|W:|E:)" || true
  fi
  BOOTSTRAP_PKGS+=(ansible)
else
  warn "Unknown Debian version '${DEBIAN_VERSION}'. Will attempt to install ansible from main repo."
  BOOTSTRAP_PKGS+=(ansible)
fi

if [[ ${#BOOTSTRAP_PKGS[@]} -gt 0 ]]; then
  info "Installing: ${BOOTSTRAP_PKGS[*]}"

  # Memory check — apt+ansible unpacked needs ~400MB.  Warn if available RAM
  # is below 512MB; the OOM killer will silently kill apt otherwise.
  MEM_AVAIL_KB=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)
  if [[ -n "$MEM_AVAIL_KB" && "$MEM_AVAIL_KB" -lt 524288 ]]; then
    warn "Only $(( MEM_AVAIL_KB / 1024 ))MB RAM available — ansible install needs ~400MB."
    warn "If apt gets killed (OOM), free memory and re-run the script."
  fi

  APT_LOG=$(mktemp /tmp/ansibleme-apt-XXXXXX.log)
  if DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
      -o Dpkg::Options::="--force-confold" \
      -o Dpkg::Options::="--force-confdef" \
      -o Dpkg::Use-Pty=0 \
      --no-install-recommends \
      "${BOOTSTRAP_PKGS[@]}" > "$APT_LOG" 2>&1; then
    success "Packages installed."
    rm -f "$APT_LOG"
  else
    APT_RC=$?
    warn "apt-get install failed (exit ${APT_RC}) -- last 20 lines of log:"
    tail -20 "$APT_LOG" >&2
    warn "Full log: ${APT_LOG}"
    die "Package installation failed. Fix the above and re-run."
  fi
else
  success "All required packages already present."
fi

# ------------------------------------------------------------------------------
# 1a. Environment
# ------------------------------------------------------------------------------
section "1a. Environment"

ENV_LONG=""
if [[ -s /etc/.environment ]]; then
  ENV_LONG="$(cat /etc/.environment)"
  if [[ -z "$ENV_LONG" ]]; then
    warn "/etc/.environment is empty — defaulting to production"
    ENV_LONG="production"
  else
    info "Environment loaded from file: ${ENV_LONG}"
  fi
else
  read -rp "  Environment ((p)roduction, (s)taging, (d)evelopment) [default: production]: " ENV
  ENV="${ENV,,}"
  case "$ENV" in
    p) ENV_LONG="production" ;;
    s) ENV_LONG="staging" ;;
    d) ENV_LONG="development" ;;
    *) warn "Invalid or empty — defaulting to production"; ENV_LONG="production" ;;
  esac
  echo "$ENV_LONG" > /etc/.environment
  success "Environment set to: ${ENV_LONG}"
fi

# ------------------------------------------------------------------------------
# 1b. Network configuration
# vRACK is the OVH provisioning/bootstrap network (192.168.139.0/24).
# Gateway is .254 (OVH vRACK default).
# Bootstrap web server lives at VRACK_NET.50.
# This is separate from the CLD site LAN (192.168.69.0/24).
# ------------------------------------------------------------------------------
section "1b. Network configuration (vRACK / provisioning)"

read -rp "  vRACK provisioning subnet (first 3 octets) [${VRACK_NET_DEFAULT}]: " VRACK_NET_INPUT
VRACK_NET="${VRACK_NET_INPUT:-${VRACK_NET_DEFAULT}}"

read -rp "  vRACK gateway last octet [${VRACK_GW_DEFAULT}]: " GW_OCTET_INPUT
GW_OCTET="${GW_OCTET_INPUT:-${VRACK_GW_DEFAULT}}"
VRACK_GW="${VRACK_NET}.${GW_OCTET}"

# Bootstrap web server on the vRACK (serves devices.csv, sites.csv, etc.)
VRACK_SERVER="${VRACK_NET}.50"

# EXAANSCLD001 lives at 192.168.69.9 on the CLD LAN, but its provisioning
# (vRACK) interface also gets a static IP on 192.168.139.x for management.
# The ansible node's vRACK IP defaults to .9 per convention.
read -rp "  Static vRACK IP for this node [${VRACK_NET}.9]: " NODE_IP_INPUT
NODE_STATIC_IP="${NODE_IP_INPUT:-${VRACK_NET}.9}"

# Detect which interface is on the vRACK subnet
info "Detecting interface on vRACK network (${VRACK_NET}.x)..."
PROV_IFACE=""
for iface in $(ls /sys/class/net/); do
  [[ "$iface" == "lo" ]] && continue
  ip_addr=$(ip -4 addr show "$iface" 2>/dev/null \
    | grep -oP "(?<=inet\s)${VRACK_NET//./\\.}\.\d+" | head -1)
  if [[ -n "$ip_addr" ]]; then
    PROV_IFACE="$iface"
    success "Detected vRACK interface: ${PROV_IFACE} (currently ${ip_addr})"
    break
  fi
done

if [[ -z "$PROV_IFACE" ]]; then
  warn "Could not auto-detect vRACK interface."
  AVAILABLE_IFACES=($(ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$' | grep -v '@'))
  read -rp "  Enter interface name (available: ${AVAILABLE_IFACES[*]}): " PROV_IFACE
  PROV_IFACE="${PROV_IFACE:-${AVAILABLE_IFACES[0]:-ens33}}"
fi

# IP collision check
info "Checking whether ${NODE_STATIC_IP} is already in use..."
if ip_in_use "${NODE_STATIC_IP}"; then
  CURRENT_IPS=$(hostname -I)
  if echo "$CURRENT_IPS" | grep -qw "${NODE_STATIC_IP}"; then
    info "${NODE_STATIC_IP} is already assigned to this host — continuing."
  else
    die "${NODE_STATIC_IP} is already in use by another host. Resolve the conflict first."
  fi
else
  success "${NODE_STATIC_IP} is free — proceeding."
fi

# Pin interface name via systemd .link so renames survive reboots
PROV_MAC=$(cat "/sys/class/net/${PROV_IFACE}/address" 2>/dev/null)
info "Pinning ${PROV_IFACE} (MAC ${PROV_MAC}) via systemd .link..."
mkdir -p /etc/systemd/network
cat > /etc/systemd/network/10-ansible-prov.link <<EOF
# Example Music -- vRACK interface pin
# Written by ansibleme.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# MAC: ${PROV_MAC}  interface: ${PROV_IFACE}
[Match]
MACAddress=${PROV_MAC}
[Link]
Name=${PROV_IFACE}
EOF
success "Interface pin written."

# Configure static IP via NetworkManager
info "Configuring static IP via NetworkManager..."

systemctl disable networking.service 2>/dev/null || true
systemctl mask    networking.service 2>/dev/null || true
systemctl mask    "ifup@${PROV_IFACE}.service" 2>/dev/null || true

if [[ -f /etc/network/interfaces ]]; then
  if grep -qE "^(auto|allow-|iface)\s+${PROV_IFACE}" /etc/network/interfaces 2>/dev/null; then
    warn "Removing ifupdown stanza for ${PROV_IFACE} from /etc/network/interfaces..."
    cp -n /etc/network/interfaces /etc/network/interfaces.bak
    sed -i "/^auto\s\+${PROV_IFACE}\b/d"    /etc/network/interfaces
    sed -i "/^allow-.*\s${PROV_IFACE}\b/d"  /etc/network/interfaces
    sed -i "/^iface\s\+${PROV_IFACE}\b/,/^[^[:space:]]/{ /^iface\s\+${PROV_IFACE}\b/d; /^[^[:space:]]/!d; }" \
      /etc/network/interfaces
    success "Cleaned /etc/network/interfaces"
  fi
fi

NM_CONF="/etc/NetworkManager/NetworkManager.conf"
if grep -q "managed=false" "${NM_CONF}" 2>/dev/null; then
  warn "NetworkManager.conf has managed=false -- fixing..."
  sed -i "s/managed=false/managed=true/" "${NM_CONF}"
fi

systemctl restart NetworkManager
sleep 3

nmcli con delete "ansible-static" 2>/dev/null || true
while IFS=: read -r profile device rest; do
  [[ -z "${profile}" ]] && continue
  if [[ "${device}" == "--" || "${profile}" == *"Wired connection"* || "${profile}" == *"Ifupdown"* ]]; then
    warn "Deleting stale NM profile: ${profile}"
    nmcli con delete "${profile}" 2>/dev/null || true
  fi
done < <(nmcli -t -f NAME,DEVICE con show)

# DNS points at the CLD BIND9 server (192.168.139.8) on the vRACK.
# This is correct and intentional — all hosts use this as upstream DNS.
nmcli con add type ethernet ifname "${PROV_IFACE}" con-name "ansible-static" \
  ipv4.method manual \
  ipv4.addresses "${NODE_STATIC_IP}/24" \
  ipv4.gateway "${VRACK_GW}" \
  ipv4.dns "192.168.139.8" \
  ipv4.dns-search "jukebox.internal" \
  ipv6.method ignore \
  connection.autoconnect yes \
  connection.autoconnect-priority 100 \
  && success "NM profile ansible-static written — will apply on reboot." \
  || warn "nmcli con add returned non-zero — check: nmcli connection show ansible-static"

warn "Static IP will take full effect on reboot."
warn "If at local console (not SSH): nmcli con up ansible-static"

# ------------------------------------------------------------------------------
# 1c. Hostname
# ------------------------------------------------------------------------------
section "1c. Hostname"

info "Detecting hostname for this ansible node..."
CURRENT_HOSTNAME=$(hostname -s)
SUGGESTED_HOSTNAME=""

if [[ "${CURRENT_HOSTNAME}" =~ ^[Ee][Xx][Aa] ]]; then
  SUGGESTED_HOSTNAME="${CURRENT_HOSTNAME^^}"
  info "Detected EXA-convention hostname: ${SUGGESTED_HOSTNAME}"
else
  SUGGESTED_HOSTNAME="EXAANSCLD001"
  warn "Current hostname '${CURRENT_HOSTNAME}' does not match EXA* convention."
fi

read -rp "  Hostname for this ansible node [${SUGGESTED_HOSTNAME}]: " HOSTNAME_INPUT
THIS_HOSTNAME="${HOSTNAME_INPUT:-${SUGGESTED_HOSTNAME}}"
THIS_HOSTNAME="${THIS_HOSTNAME^^}"

info "Setting hostname to ${THIS_HOSTNAME}..."
hostnamectl set-hostname "${THIS_HOSTNAME}"
grep -q "${THIS_HOSTNAME,,}" /etc/hosts 2>/dev/null || \
  echo "127.0.1.1  ${THIS_HOSTNAME,,}.jukebox.internal  ${THIS_HOSTNAME,,}" >> /etc/hosts
success "Hostname set to ${THIS_HOSTNAME}."

# ------------------------------------------------------------------------------
# 2. Shell environment
# ------------------------------------------------------------------------------
section "2. Shell environment"

if id "$ANSIBLE_USER" &>/dev/null && [[ ! -f "${ANSIBLE_HOME}/.zshrc" ]]; then
  info "Setting up zsh for ${ANSIBLE_USER} user..."
  cat > "${ANSIBLE_HOME}/.zshrc" <<'ZSHRC'
export TERM=xterm-256color
export EDITOR=vim
export VISUAL=vim
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd extendedglob notify interactivecomments
setopt AUTO_CONTINUE LONG_LIST_JOBS
bindkey -e
autoload -Uz compinit && compinit
autoload -Uz colors && colors
bindkey "\e[1~" beginning-of-line;  bindkey "\e[4~" end-of-line
bindkey "\e[H"  beginning-of-line;  bindkey "\e[F"  end-of-line
bindkey "\eOH"  beginning-of-line;  bindkey "\eOF"  end-of-line
bindkey "\e[1;5C" forward-word;     bindkey "\e[1;5D" backward-word
bindkey "\e[5C"   forward-word;     bindkey "\e[5D"   backward-word
bindkey "\e\e[C"  forward-word;     bindkey "\e\e[D"  backward-word
bindkey "\e[3~" delete-char
PROMPT='
%F{green}%m%f:%F{cyan}%~%f> '
alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias ap='ansible-playbook'
alias ai='ansible-inventory'
alias ag='ansible-galaxy'
if (( $+commands[grc] )); then
  GRC_ALIASES=true
  [[ -f /etc/profile.d/grc.sh ]] && source /etc/profile.d/grc.sh
fi
ZSHRC
  chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_HOME}/.zshrc"
  chsh -s "$(command -v zsh)" "$ANSIBLE_USER"
  success "zsh configured for ${ANSIBLE_USER}."
fi

if [[ ! -f /root/.zshrc ]]; then
  info "Setting up zsh for root..."
  cat > /root/.zshrc <<'ZSHRC'
export TERM=xterm-256color
export EDITOR=vim
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd extendedglob notify interactivecomments
setopt AUTO_CONTINUE LONG_LIST_JOBS
bindkey -e
autoload -Uz compinit && compinit
autoload -Uz colors && colors
bindkey "\e[1~" beginning-of-line;  bindkey "\e[4~" end-of-line
bindkey "\e[H"  beginning-of-line;  bindkey "\e[F"  end-of-line
bindkey "\eOH"  beginning-of-line;  bindkey "\eOF"  end-of-line
bindkey "\e[3~" delete-char
PROMPT='
%F{red}%m%f:%F{cyan}%~%f# '
alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias ap='ansible-playbook'
if (( $+commands[grc] )); then
  GRC_ALIASES=true
  [[ -f /etc/profile.d/grc.sh ]] && source /etc/profile.d/grc.sh
fi
ZSHRC
  chsh -s "$(command -v zsh)" root
  success "zsh configured for root."
fi

# ------------------------------------------------------------------------------
# 3. Site / node identity
# ------------------------------------------------------------------------------
section "3. Node identity"

DETECTED_SITE=""
HOSTNAME_NOW=$(hostname)
if [[ "$HOSTNAME_NOW" =~ ^EXA[A-Z]{3}([A-Z]{3})[0-9]{3}$ ]]; then
  DETECTED_SITE="${BASH_REMATCH[1]}"
fi

echo -e "${CYAN}Known site codes:${NC}"
echo -e "${CYAN}  $(echo "${!SITE_OCTET[@]}" | tr ' ' '\n' | sort | tr '\n' ' ')${NC}"
echo

SITE_CODE=""
SUBNET=""
while true; do
  if [[ -n "$DETECTED_SITE" && -v SITE_OCTET[$DETECTED_SITE] ]]; then
    read -rp "Site code (detected from hostname: ${DETECTED_SITE}, press Enter to accept): " SITE_INPUT
    SITE_INPUT="${SITE_INPUT:-${DETECTED_SITE}}"
  else
    read -rp "Enter site code for this node (e.g. CLD, FAL): " SITE_INPUT
  fi
  SITE_CODE="${SITE_INPUT^^}"

  if [[ -v SITE_OCTET[$SITE_CODE] ]]; then
    WG_OCTET="${SITE_OCTET[$SITE_CODE]}"
    SUBNET="192.168.${WG_OCTET}"
    SITE_DISPLAY_CITY="${SITE_CITY[$SITE_CODE]:-${SITE_CODE}}"
    SITE_DISPLAY_COUNTRY="${SITE_COUNTRY[$SITE_CODE]:-Unknown}"
    SITE_DISPLAY_ENTITY="${SITE_ENTITY[$SITE_CODE]:-Example Music}"
    echo -e "  ${GREEN}→ ${SITE_CODE}: ${SITE_DISPLAY_CITY}, ${SITE_DISPLAY_COUNTRY} — ${SITE_DISPLAY_ENTITY}${NC}"
    echo -e "  ${GREEN}→ site LAN subnet ${SUBNET}.0/24${NC}"
    break
  else
    warn "Unknown site code '${SITE_CODE}'. Try again."
  fi
done

# ------------------------------------------------------------------------------
# 4. ansible user
# ------------------------------------------------------------------------------
section "4. Ansible user"

if ! id "$ANSIBLE_USER" &>/dev/null; then
  info "Creating ${ANSIBLE_USER} user..."
  useradd --create-home --shell "$(command -v zsh)" "$ANSIBLE_USER"
  success "User ${ANSIBLE_USER} created."
else
  success "User ${ANSIBLE_USER} already exists."
fi

if getent group kvm &>/dev/null; then
  if ! id -nG "$ANSIBLE_USER" | grep -qw kvm; then
    usermod -a -G kvm "$ANSIBLE_USER"
    info "Added ${ANSIBLE_USER} to kvm group."
  fi
fi

SUDOERS_FILE="/etc/sudoers.d/ansible"
if [[ ! -f "$SUDOERS_FILE" ]]; then
  echo "ansible ALL=(ALL) NOPASSWD: ALL" > "$SUDOERS_FILE"
  chmod 0440 "$SUDOERS_FILE"
  success "sudoers drop-in written."
else
  success "sudoers drop-in already present."
fi

# ------------------------------------------------------------------------------
# 5. Directory scaffold
# ------------------------------------------------------------------------------
section "5. Directory scaffold"

REPO_DIR="${ANSIBLE_HOME}/example-music-infra"
REPO_URL="https://github.com/knightmare2600/example-music-infra"

# ── Clone or update the repo ─────────────────────────────────────────────────
if [[ -d "${REPO_DIR}/.git" ]]; then
  info "Repo already present at ${REPO_DIR} — pulling latest..."
  git -C "${REPO_DIR}" pull --ff-only || warn "git pull failed; continuing with existing clone."
else
  info "Cloning ${REPO_URL} into ${REPO_DIR}..."
  git clone "${REPO_URL}" "${REPO_DIR}"
fi

# ── Symlink ansible/ subfolder ────────────────────────────────────────────────
if [[ -L "${ANSIBLE_DIR}" ]]; then
  info "Symlink ${ANSIBLE_DIR} already exists — skipping."
elif [[ -d "${ANSIBLE_DIR}" ]]; then
  warn "${ANSIBLE_DIR} is a real directory, not a symlink — leaving it in place."
  warn "Remove it manually if you want to switch to the symlinked repo layout."
else
  ln -s "${REPO_DIR}/ansible" "${ANSIBLE_DIR}"
  info "Symlinked /home/ansible/ansible -> ${REPO_DIR}/ansible"
fi

# ── Runtime dirs not provided by the repo ────────────────────────────────────
# playbooks/, handlers/, vars/, host_vars/, docs/, files/ come from the clone.
# configs/ and callback_plugins/ are local-only; group_vars/ holds generated content.
mkdir -p \
  "${CONFIGS_DIR}/inventory" \
  "${CALLBACK_DIR}" \
  "${ANSIBLE_DIR}/group_vars/all" \
  "${ANSIBLE_DIR}/group_vars/linux" \
  "${ANSIBLE_DIR}/group_vars/pvenodes" \
  "${ANSIBLE_DIR}/group_vars/firewalls" \
  "${ANSIBLE_DIR}/group_vars/rudder_servers" \
  "${ANSIBLE_DIR}/group_vars/rudder_relays" \
  "${ANSIBLE_DIR}/group_vars/windows_nodes" \
  "${ANSIBLE_DIR}/group_vars/windows" \
  "${ANSIBLE_DIR}/group_vars/windows_server" \
  "${ANSIBLE_DIR}/group_vars/windows_desktop" \
  "${ANSIBLE_DIR}/group_vars/windows_laptop" \
  "${ANSIBLE_DIR}/group_vars/windows_dc"

chown -R "${ANSIBLE_USER}:${ANSIBLE_USER}" "${REPO_DIR}"
chown -R "${ANSIBLE_USER}:${ANSIBLE_USER}" "${CONFIGS_DIR}"
[[ -d "${CALLBACK_DIR}" ]] && chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${CALLBACK_DIR}"
success "Repo cloned and symlinked; runtime dirs created."

# ------------------------------------------------------------------------------
# 5b. Data files — sites.csv and devices.csv
# ------------------------------------------------------------------------------
section "5b. Data files"

CANONICAL_DIR="/etc/example-music"
mkdir -p "${CANONICAL_DIR}"

# ── devices.csv ──────────────────────────────────────────────────────────────
DEVICES_CANONICAL="${CANONICAL_DIR}/devices.csv"
DEVICES_URL="http://${VRACK_SERVER}/proxmox/devices.csv"

if [[ -f "${DEVICES_CANONICAL}" ]]; then
  success "devices.csv found at ${DEVICES_CANONICAL}"
else
  info "devices.csv not found at ${DEVICES_CANONICAL} — fetching from ${DEVICES_URL}..."
  if wget -q --timeout=15 -O "${DEVICES_CANONICAL}" "${DEVICES_URL}" 2>/dev/null; then
    success "Downloaded to ${DEVICES_CANONICAL}."
  else
    warn "Could not download devices.csv from ${DEVICES_URL}."
    warn "Place devices.csv at ${DEVICES_CANONICAL} before running bind9-dns.yml."
    warn "Source: bootstrap/web/proxmox/devices.csv in the infrastructure repo."
  fi
fi

# ── sites.csv ────────────────────────────────────────────────────────────────
SITES_CANONICAL="${CANONICAL_DIR}/sites.csv"
if [[ ! -f "${SITES_CANONICAL}" ]]; then
  if [[ -n "${SITES_CSV:-}" && -f "${SITES_CSV}" ]]; then
    cp "${SITES_CSV}" "${SITES_CANONICAL}"
    success "Installed sites.csv to ${SITES_CANONICAL} from ${SITES_CSV}."
  else
    info "Fetching sites.csv from vRACK bootstrap server..."
    SITES_URL="http://${VRACK_SERVER}/proxmox/sites.csv"
    if wget -q --timeout=15 -O "${SITES_CANONICAL}" "${SITES_URL}" 2>/dev/null; then
      success "Downloaded sites.csv to ${SITES_CANONICAL}."
    else
      warn "Could not download sites.csv from ${SITES_URL} — already loaded from ${SITES_CSV:-/etc/example-music/sites.csv}."
    fi
  fi
fi

# ------------------------------------------------------------------------------
# 6. SSH keypair
# ------------------------------------------------------------------------------
section "6. SSH keypair"

ANSIBLE_PUBKEY=""

if [[ -f "$KEY_FILE" ]]; then
  EXISTING_PUB=$(cat "$KEY_PUB" 2>/dev/null || true)
  success "SSH key already exists at ${KEY_FILE}"
  echo -e "  ${CYAN}Public key: ${NC}${EXISTING_PUB}"
  read -rp "Replace the existing keypair? [y/N] " REGEN_KEY
  if [[ "${REGEN_KEY,,}" != "y" ]]; then
    ANSIBLE_PUBKEY="$EXISTING_PUB"
    info "Keeping existing keypair."
  else
    info "Generating new SSH keypair for ansible user..."
    sudo -u "$ANSIBLE_USER" ssh-keygen -t rsa -b 4096 -C "${ANSIBLE_USER}@$(hostname)" -f "$KEY_FILE" -N ""
    chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$KEY_FILE" "$KEY_PUB"
    chmod 600 "$KEY_FILE"
    chmod 644 "$KEY_PUB"
    ANSIBLE_PUBKEY=$(cat "$KEY_PUB")
    success "Keypair regenerated."
  fi
else
  echo
  echo -e "  ${CYAN}SSH keypair options:${NC}"
  echo -e "  ${WHITE}1)${NC} Generate a new keypair on this host (recommended)"
  echo -e "  ${WHITE}2)${NC} Paste an existing PUBLIC key (private key must be copied separately)"
  echo
  read -rp "  Choice [1]: " KEY_MODE
  KEY_MODE="${KEY_MODE:-1}"

  if [[ "$KEY_MODE" == "2" ]]; then
    echo -e "  ${CYAN}Paste the public key (ssh-rsa ... comment) and press Enter:${NC}"
    read -rp "  > " PASTED_KEY
    if [[ -z "$PASTED_KEY" ]]; then
      die "No key pasted — aborting."
    fi
    mkdir -p "${CONFIGS_DIR}"
    echo "$PASTED_KEY" > "$KEY_PUB"
    chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$KEY_PUB"
    chmod 644 "$KEY_PUB"
    ANSIBLE_PUBKEY="$PASTED_KEY"

    echo
    echo -e "${YELLOW}  +==========================================================================================================+${NC}"
    echo -e "${YELLOW}  |  PRIVATE KEY REQUIRED — copy it manually                                                                 |${NC}"
    echo -e "${YELLOW}  +==========================================================================================================+${NC}"
    echo -e "${YELLOW}  |${NC}  The matching private key must be placed at:"
    echo -e "${YELLOW}  |${NC}"
    echo -e "${YELLOW}  |${NC}    ${WHITE}${KEY_FILE}${NC}"
    echo -e "${YELLOW}  |${NC}"
    echo -e "${YELLOW}  |${NC}  From your workstation:"
    echo -e "${YELLOW}  |${NC}    ${WHITE}scp ~/.ssh/ansible-id_rsa ${ANSIBLE_USER}@$(hostname -I | awk '{print $1}'):${KEY_FILE}${NC}"
    echo -e "${YELLOW}  |${NC}"
    echo -e "${YELLOW}  |${NC}  Then on this host:"
    echo -e "${YELLOW}  |${NC}    ${WHITE}chown ${ANSIBLE_USER}:${ANSIBLE_USER} ${KEY_FILE}${NC}"
    echo -e "${YELLOW}  |${NC}    ${WHITE}chmod 600 ${KEY_FILE}${NC}"
    echo -e "${YELLOW}  |${NC}"
    echo -e "${YELLOW}  |${NC}  ${RED}Never paste a private key into this script or any terminal prompt.${NC}"
    echo -e "${YELLOW}  +==========================================================================================================+${NC}"
    echo
    read -rp "  Press Enter once you understand and will complete this step manually... " _ACK
    warn "Continuing setup. ansible-playbook and ansible ad-hoc runs will NOT work"
    warn "until ${KEY_FILE} is in place with the correct permissions."
  else
    info "Generating SSH keypair for ansible user..."
    mkdir -p "${CONFIGS_DIR}"
    sudo -u "$ANSIBLE_USER" ssh-keygen -t rsa -b 4096 -C "${ANSIBLE_USER}@$(hostname)" -f "$KEY_FILE" -N ""
    chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$KEY_FILE" "$KEY_PUB"
    chmod 600 "$KEY_FILE"
    chmod 644 "$KEY_PUB"
    ANSIBLE_PUBKEY=$(cat "$KEY_PUB")
    success "Keypair generated."
  fi
fi

echo
echo -e "${YELLOW}  ╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${YELLOW}  ║    ANSIBLE PUBLIC KEY — distribute to managed hosts   ║${NC}"
echo -e "${YELLOW}  ╚═══════════════════════════════════════════════════════╝${NC}"
echo -e "${GREEN}${ANSIBLE_PUBKEY}${NC}"
echo -e "${CYAN}  (also saved at ${KEY_PUB})${NC}"
echo

# Ensure the ansible user's own ~/.ssh has this key
ANSIBLE_SSH_DIR="${ANSIBLE_HOME}/.ssh"
mkdir -p "$ANSIBLE_SSH_DIR"
if ! grep -qF "$ANSIBLE_PUBKEY" "${ANSIBLE_SSH_DIR}/authorized_keys" 2>/dev/null; then
  [[ -s "${ANSIBLE_SSH_DIR}/authorized_keys" ]] && \
    tail -c1 "${ANSIBLE_SSH_DIR}/authorized_keys" | grep -qP '[^\n]' && \
    printf '\n' >> "${ANSIBLE_SSH_DIR}/authorized_keys"
  printf '%s\n' "$ANSIBLE_PUBKEY" >> "${ANSIBLE_SSH_DIR}/authorized_keys"
fi
chmod 700 "$ANSIBLE_SSH_DIR"
chmod 600 "${ANSIBLE_SSH_DIR}/authorized_keys"
chown -R "${ANSIBLE_USER}:${ANSIBLE_USER}" "$ANSIBLE_SSH_DIR"
success "Public key installed in ${ANSIBLE_USER}'s authorized_keys."

cp "$SUDOERS_FILE" "${FILES_DIR}/sudoer_ansible"
chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${FILES_DIR}/sudoer_ansible"
if visudo -cf "$SUDOERS_FILE" &>/dev/null; then
  chmod 0440 "$SUDOERS_FILE"
  chown root:root "$SUDOERS_FILE"
  success "sudoers drop-in validated and applied to this host."
else
  warn "sudoers validation failed — check ${SUDOERS_FILE} manually."
fi

# ------------------------------------------------------------------------------
# 6b. Download exa_pretty callback plugin from GitHub
# ------------------------------------------------------------------------------
section "6b. exa_pretty callback plugin"

EXA_PRETTY_DEST="${CALLBACK_DIR}/exa_pretty.py"

info "Downloading exa_pretty.py from GitHub..."
if wget -q --timeout=30 -O "${EXA_PRETTY_DEST}" "${EXA_PRETTY_URL}" 2>/dev/null; then
  chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${EXA_PRETTY_DEST}"
  chmod 644 "${EXA_PRETTY_DEST}"
  success "exa_pretty.py downloaded to ${EXA_PRETTY_DEST}"
else
  warn "Could not download exa_pretty.py from GitHub."
  warn "URL: ${EXA_PRETTY_URL}"
  warn "Clone the repo and copy it manually:"
  warn "  cp example_music_infra/ansible/callback_plugins/exa_pretty.py ${EXA_PRETTY_DEST}"
  warn "ansible.cfg references this file — stdout_callback will fall back to default until it is present."
fi

# ------------------------------------------------------------------------------
# 7. PVE node discovery
# ------------------------------------------------------------------------------
section "7. PVE node discovery"

echo -e "${CYAN}  PVE nodes follow the standard octet convention:${NC}"
echo -e "${CYAN}    .5 = primary PVE node    (EXAPVE{SITE}001)${NC}"
echo -e "${CYAN}    .6 = secondary PVE node  (EXAPVE{SITE}002)${NC}"
echo -e "${CYAN}  All sites from the CSV will be pre-populated into [pvenodes].${NC}"
echo -e "${CYAN}  You will be asked for any additional nodes not covered by the CSV.${NC}"
echo

PVE_NODES=()

for site_code in $(echo "${!SITE_OCTET[@]}" | tr ' ' '\n' | sort); do
  oct="${SITE_OCTET[$site_code]}"
  city="${SITE_CITY[$site_code]:-$site_code}"
  [[ -z "$oct" ]] && continue
  PVE_NODES+=("192.168.${oct}.5   # ${site_code} -- ${city} (primary)")
  PVE_NODES+=("192.168.${oct}.6   # ${site_code} -- ${city} (secondary)")
done

success "Pre-populated ${#SITE_OCTET[@]} sites x 2 nodes = $((${#SITE_OCTET[@]} * 2)) PVE entries from CSV."
echo -e "${CYAN}  These cover 192.168.x.5 and .6 for every site.${NC}"
echo -e "${CYAN}  Not all sites will have physical PVE nodes -- comment out entries as needed.${NC}"
echo

echo -e "${CYAN}  Enter any additional PVE node IPs not in the CSV. Blank to skip.${NC}"
echo

while true; do
  read -rp "  Additional PVE node IP (blank to finish): " PVE_INPUT
  [[ -z "$PVE_INPUT" ]] && break
  PVE_NODES+=("$PVE_INPUT")
  success "Added: ${PVE_INPUT}"
done

# ------------------------------------------------------------------------------
# 7b. Clear stale known_hosts entries before any SSH activity
# ------------------------------------------------------------------------------
section "7b. Clearing stale SSH host keys"

ANSIBLE_KNOWN_HOSTS="${ANSIBLE_HOME}/.ssh/known_hosts"
mkdir -p "${ANSIBLE_HOME}/.ssh"
touch "$ANSIBLE_KNOWN_HOSTS"
chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$ANSIBLE_KNOWN_HOSTS"
chmod 644 "$ANSIBLE_KNOWN_HOSTS"

PRESCAN_IPS=()
for site_code in "${!SITE_OCTET[@]}"; do
  oct="${SITE_OCTET[$site_code]}"
  [[ -z "$oct" ]] && continue
  PRESCAN_IPS+=("192.168.${oct}.5" "192.168.${oct}.6")
  [[ -n "${SITE_DC[$site_code]:-}" ]] && PRESCAN_IPS+=("${SITE_DC[$site_code]}")
  [[ -n "${SITE_FW[$site_code]:-}" ]] && PRESCAN_IPS+=("${SITE_FW[$site_code]}")
done
PRESCAN_IPS+=("$(hostname -I | awk '{print $1}')")

CLEARED=0
for ip in "${PRESCAN_IPS[@]}"; do
  [[ -z "$ip" ]] && continue
  if ssh-keygen -R "$ip" -f "$ANSIBLE_KNOWN_HOSTS" &>/dev/null; then
    (( CLEARED++ )) || true
  fi
  if [[ -f /etc/ssh/ssh_known_hosts ]]; then
    ssh-keygen -R "$ip" -f /etc/ssh/ssh_known_hosts &>/dev/null || true
  fi
done
success "Checked ${#PRESCAN_IPS[@]} known address(es) for stale host keys."
info "accept-new will trust each host's current key on first connect."

# ------------------------------------------------------------------------------
# 8. Infrastructure discovery
# ------------------------------------------------------------------------------
section "8. Infrastructure discovery"

if [[ ! -f "$KEY_FILE" ]]; then
  warn "No private key found at ${KEY_FILE} yet."
  warn "An SSH subnet scan (option A below) will fail to reach any host until"
  warn "the private key is placed there. Either skip the scan and choose B or C,"
  warn "or place the private key now in another terminal before continuing."
  echo
fi

echo -e "${CYAN}  The inventory can be populated two ways:${NC}"
echo -e "${CYAN}  A) SSH subnet scan  — discovers live hosts, classifies by role, builds groups${NC}"
echo -e "${CYAN}  B) CSV-only fill    — builds inventory from sites.csv without scanning${NC}"
echo -e "${CYAN}  C) Skip             — leave inventory empty (fill manually later)${NC}"
echo
read -rp "  Choose [A/b/c]: " DISC_MODE
DISC_MODE="${DISC_MODE,,}"

declare -A DISC_HOSTS_BY_GROUP
DISC_UNKNOWNS=""

_classify_host() {
  local ip="$1" ptr="$2"
  local last_octet="${ip##*.}"
  local third_octet
  third_octet=$(echo "$ip" | awk -F. '{print $3}')

  # vRACK net (192.168.139.x) — known roles by last octet
  if [[ "$third_octet" == "139" ]]; then
    case "$last_octet" in
      8)     echo "srvnodes"     ; return ;;  # EXADNSCLD001 — DNS/BIND9
      9)     echo "ansiblehosts" ; return ;;  # EXAANSCLD001 — Ansible control node
      10|11) echo "dcs"          ; return ;;  # EXADCSCLD001/002 (vRACK face)
      *)     echo "srvnodes"     ; return ;;  # other CLD infra on vRACK
    esac
  fi

  # CLD site LAN (192.168.69.x)
  if [[ "$third_octet" == "69" ]]; then
    case "$last_octet" in
      9)     echo "ansiblehosts" ; return ;;  # EXAANSCLD001 CLD LAN face
      10|11) echo "dcs"          ; return ;;  # EXADCSCLD001/002 CLD LAN face
      *)     echo "srvnodes"     ; return ;;
    esac
  fi

  case "$last_octet" in
    10|11) echo "dcs"       ; return ;;
    253)   echo "firewalls" ; return ;;
    48)    echo "pbx"       ; return ;;
  esac

  echo "unknowns"
}

_scan_subnet() {
  local subnet="$1"
  local key="$2"

  if ! command -v prips &>/dev/null; then
    warn "prips not found — installing..."
    apt-get install -y -qq prips > /dev/null
  fi

  echo -e "  ${CYAN}Scanning ${subnet} ...${NC}"
  local found=0

  for ip in $(prips "$subnet"); do
    [[ "$ip" =~ \.(0|255)$ ]] && continue

    printf '    [*] %-17s ' "$ip"
    output=$(ssh -o BatchMode=yes \
                 -o ConnectTimeout=2 \
                 -o StrictHostKeyChecking=accept-new \
                 -o UserKnownHostsFile="${ANSIBLE_HOME}/.ssh/known_hosts" \
                 -i "$KEY_FILE" \
                 "ansible@${ip}" true 2>&1)
    rc=$?

    if [[ $rc -eq 0 ]]; then
      ptr=$(host "$ip" 2>/dev/null | awk '/pointer/ {print $NF}' | sed 's/\.$//')
      [[ -z "$ptr" ]] && ptr="(no PTR)"
      group=$(_classify_host "$ip" "$ptr")
      label="${ip}  # ${ptr}"
      printf "${GREEN}%-20s${NC} → [%s]\n" "UP" "$group"
      DISC_HOSTS_BY_GROUP[$group]+="${label}"$'\n'
      (( found++ )) || true
    else
      if echo "$output" | grep -qi "permission denied"; then
        printf "${YELLOW}AUTH FAIL${NC}\n"
        DISC_UNKNOWNS+="${ip}  # AUTH FAILED — key not deployed yet"$'\n'
      elif echo "$output" | grep -qi "connection refused"; then
        printf "REFUSED\n"
      elif echo "$output" | grep -qi "no route\|Network unreachable"; then
        printf "NO ROUTE\n"
      else
        printf "DOWN\n"
      fi
    fi
  done

  echo -e "  ${GREEN}Scan of ${subnet} complete — ${found} host(s) reachable via ansible key.${NC}"
}

if [[ "$DISC_MODE" != "b" && "$DISC_MODE" != "c" ]]; then
  echo
  echo -e "${CYAN}  Which subnets to scan? (select all that apply)${NC}"
  echo -e "${CYAN}  Note: WireGuard tunnel subnets (10.0.x.0/24) only work if WG is already up.${NC}"
  echo -e "${CYAN}  Note: Site LAN subnets (192.168.x.0/24) only reachable if routing exists.${NC}"
  echo
  echo -e "  ${WHITE}1)${NC} vRACK provisioning network      (${VRACK_NET}.0/24)"
  echo -e "  ${WHITE}2)${NC} CLD site LAN                    (192.168.69.0/24)"
  echo -e "  ${WHITE}3)${NC} All site LAN subnets from CSV   (192.168.x.0/24 — one per site, ~48 scans)"
  echo -e "  ${WHITE}4)${NC} WireGuard tunnel subnets        (10.0.x.0/24 — requires WG up)"
  echo -e "  ${WHITE}5)${NC} Custom subnet(s)                (you specify)"
  echo
  read -rp "  Enter choices space-separated [e.g. 1 2, default: 1]: " SCAN_CHOICE
  SCAN_CHOICE="${SCAN_CHOICE:-1}"

  SUBNETS_TO_SCAN=()

  for choice in $SCAN_CHOICE; do
    case "$choice" in
      1)
        SUBNETS_TO_SCAN+=("${VRACK_NET}.0/24")
        ;;
      2)
        SUBNETS_TO_SCAN+=("192.168.69.0/24")
        ;;
      3)
        echo -e "  ${CYAN}Adding all ${#SITE_OCTET[@]} site LAN subnets from CSV...${NC}"
        for site_code in $(echo "${!SITE_OCTET[@]}" | tr ' ' '\n' | sort); do
          oct="${SITE_OCTET[$site_code]}"
          [[ -n "$oct" ]] && SUBNETS_TO_SCAN+=("192.168.${oct}.0/24")
        done
        ;;
      4)
        echo -e "  ${CYAN}Adding WireGuard tunnel subnets (10.0.x.0/24)...${NC}"
        for site_code in $(echo "${!SITE_OCTET[@]}" | tr ' ' '\n' | sort); do
          oct="${SITE_OCTET[$site_code]}"
          [[ -n "$oct" ]] && SUBNETS_TO_SCAN+=("10.0.${oct}.0/24")
        done
        ;;
      5)
        echo -e "  ${CYAN}Enter custom subnets, one per line (blank to finish):${NC}"
        while true; do
          read -rp "    Subnet (e.g. 10.10.0.0/24): " CUSTOM_SUBNET
          [[ -z "$CUSTOM_SUBNET" ]] && break
          SUBNETS_TO_SCAN+=("$CUSTOM_SUBNET")
        done
        ;;
      *)
        warn "Unknown choice '$choice' — skipping."
        ;;
    esac
  done

  if [[ ${#SUBNETS_TO_SCAN[@]} -eq 0 ]]; then
    warn "No subnets selected — skipping scan."
  else
    echo
    echo -e "${CYAN}  Subnets to scan:${NC}"
    for s in "${SUBNETS_TO_SCAN[@]}"; do
      echo -e "    ${CYAN}•${NC} $s"
    done
    echo
    read -rp "  Proceed with scan? [Y/n]: " CONFIRM_SCAN
    if [[ "${CONFIRM_SCAN,,}" != "n" ]]; then
      for subnet in "${SUBNETS_TO_SCAN[@]}"; do
        _scan_subnet "$subnet" "$KEY_FILE"
        echo
      done

      echo -e "${GREEN}  ── Discovery summary ──────────────────────────────────────${NC}"
      for grp in "${!DISC_HOSTS_BY_GROUP[@]}"; do
        count=$(echo "${DISC_HOSTS_BY_GROUP[$grp]}" | grep -c '\.' || true)
        echo -e "    ${GREEN}[${grp}]${NC}: ${count} host(s)"
      done
      if [[ -n "$DISC_UNKNOWNS" ]]; then
        unknown_count=$(echo "$DISC_UNKNOWNS" | grep -c '\.' || true)
        warn "${unknown_count} unclassified host(s) — will appear in [unknowns] (commented out)"
      fi
      echo
    else
      info "Scan cancelled."
    fi
  fi
fi

if [[ "$DISC_MODE" == "b" ]]; then
  echo -e "${CYAN}  Building inventory groups from CSV data (no scan)...${NC}"

  declare -A _SEEN_DC _SEEN_FW

  for site_code in $(echo "${!SITE_OCTET[@]}" | tr ' ' '\n' | sort); do
    dc_ip="${SITE_DC[$site_code]:-}"
    fw_ip="${SITE_FW[$site_code]:-}"
    city="${SITE_CITY[$site_code]:-$site_code}"

    if [[ -n "$dc_ip" ]]; then
      if [[ -n "${_SEEN_DC[$dc_ip]:-}" ]]; then
        DISC_HOSTS_BY_GROUP[dcs]="${DISC_HOSTS_BY_GROUP[dcs]//${dc_ip}  # ${_SEEN_DC[$dc_ip]}/${dc_ip}  # ${_SEEN_DC[$dc_ip]}/${site_code}}"
      else
        _SEEN_DC[$dc_ip]="${site_code} — ${city}"
        printf -v _entry "%-15s # %s — %s" "$dc_ip" "$site_code" "$city"
        DISC_HOSTS_BY_GROUP[dcs]+="${_entry}"$'\n'
      fi
    fi

    if [[ -n "$fw_ip" ]]; then
      if [[ -n "${_SEEN_FW[$fw_ip]:-}" ]]; then
        DISC_HOSTS_BY_GROUP[firewalls]="${DISC_HOSTS_BY_GROUP[firewalls]//${fw_ip}  # ${_SEEN_FW[$fw_ip]}/${fw_ip}  # ${_SEEN_FW[$fw_ip]}/${site_code}}"
      else
        _SEEN_FW[$fw_ip]="${site_code} — ${city}"
        printf -v _entry "%-15s # %s — %s" "$fw_ip" "$site_code" "$city"
        DISC_HOSTS_BY_GROUP[firewalls]+="${_entry}"$'\n'
      fi
    fi
  done

  success "CSV-derived groups built: [dcs] and [firewalls]."
  info  "[ansiblehosts] will contain this node."
  info  "[pvenodes] has been pre-populated with .5 and .6 for all ${#SITE_OCTET[@]} sites."
fi

if [[ "$DISC_MODE" != "c" ]]; then
  echo
  echo -e "${CYAN}  Add any additional groups not covered above? Press Enter on blank group name to finish.${NC}"
  echo

  while true; do
    read -rp "  Extra group name (blank to finish): " GROUP_INPUT
    [[ -z "$GROUP_INPUT" ]] && break
    CURRENT_GROUP="${GROUP_INPUT,,}"
    [[ -z "${DISC_HOSTS_BY_GROUP[$CURRENT_GROUP]+x}" ]] && DISC_HOSTS_BY_GROUP[$CURRENT_GROUP]=""
    echo -e "  ${CYAN}Enter IPs/hostnames for [${CURRENT_GROUP}], blank to move on:${NC}"
    while true; do
      read -rp "    Host: " HOST_INPUT
      [[ -z "$HOST_INPUT" ]] && break
      DISC_HOSTS_BY_GROUP[$CURRENT_GROUP]+="${HOST_INPUT}"$'\n'
    done
  done
fi

# ------------------------------------------------------------------------------
# 9. Write ansible.cfg
# ------------------------------------------------------------------------------
section "9. Writing ansible.cfg"

if [[ -f "$ANSIBLE_CFG" ]]; then
  warn "ansible.cfg already exists at ${ANSIBLE_CFG} — skipping write."
  info "Delete it and re-run to regenerate."
else

cat > "$ANSIBLE_CFG" <<EOF
# =================================================================================================
# Ansible Configuration
# Example Music Limited
#
# Purpose:
#   Central configuration for Example Music infrastructure automation.
#
# Used for:
#   - Initial host onboarding / bootstrap
#   - Inventory-driven configuration management
#   - Ongoing estate administration
#
# Environment assumptions:
#   - Hosts may be powered off at any time
#   - Inventory may be generated dynamically
#   - DNS may not exist during bootstrap
#   - SSH keys are distributed before Ansible runs
#
# Notes:
#   - Unreachable hosts are NOT ignored via ansible.cfg. That behaviour must be configured in
#     playbooks using:
#
#       ignore_unreachable: true
#
#     or handled explicitly with tasks/meta directives.
#
# Generated by ansibleme.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# =================================================================================================
[defaults]
# Automatically discover correct Python interpreter on remote systems sans warnings.
interpreter_python = auto_silent
host_key_checking  = True

# Primary inventory location.
inventory = ${CONFIGS_DIR}/inventory

# Default SSH user.
remote_user = ${ANSIBLE_USER}

# SSH private key used for authentication.
private_key_file   = ${KEY_FILE}

# Colourised human-readable task output via exa_pretty callback.
# exa_pretty.py lives in callback_plugins/ — downloaded from GitHub by ansibleme.sh.
callback_plugins   = ${CALLBACK_DIR}
stdout_callback    = exa_pretty
callback_whitelist = exa_pretty
result_format      = yaml

# Enable callback plugins.
bin_ansible_callbacks = True

# Number of parallel worker processes.
forks = 50

# SSH connection timeout (seconds). Important when hosts may be powered off.
timeout = 5

# Retry files record failed hosts for rerunning failed operations.
retry_files_enabled = True
retry_files_save_path = /tmp

# Suppress walls of skipped hosts in output.
display_skipped_hosts = False
display_failed_stderr = False

# exa_pretty callback settings
[callback_exa_pretty]
suppress_unreachable   = True
show_unreachable_hosts = False

[privilege_escalation]
# Global become is OFF. Linux hosts get become via group_vars/linux/main.yml.
# Windows hosts must never have become=true (sudo does not exist on Windows).
# This was battle-tested on 2026-06-27 — do not re-enable globally.
become        = False
become_method = sudo
become_user   = root

[ssh_connection]
# ControlMaster=auto                Reuse existing SSH sessions where possible.
# ControlPersist=60s                Keep SSH control connections alive for 60 seconds.
# StrictHostKeyChecking=accept-new  Automatically trust new, while detecting changed fingerprints.
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=accept-new

# Enable SSH pipelining. Reduces the number of SSH operations required.
pipelining = True

# Fail quickly when a host is unavailable.
connect_timeout = 5

[persistent_connection]
# Maximum command runtime.
command_timeout = 30
# Time spent retrying persistent connections.
connect_retry_timeout = 15

# =================================================================================================
# RECOMMENDED PLAYBOOK SETTINGS FOR INTERMITTENT HOSTS
# =================================================================================================
#
# Example:
#
# - hosts: all
#   gather_facts: false
#   ignore_unreachable: true
#   strategy: free
#
# Explanation:
#
# gather_facts: false         Avoid immediate failures during fact gathering.
# ignore_unreachable: true    Continue processing remaining hosts even if some nodes are offline.
# strategy: free              Allows hosts to progress independently instead of waiting for the
#                             slowest host.
# =================================================================================================
EOF

chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$ANSIBLE_CFG"
success "ansible.cfg written."

fi  # end [[ ! -f "$ANSIBLE_CFG" ]]

# ------------------------------------------------------------------------------
# 10. Write inventory
# ------------------------------------------------------------------------------
section "10. Writing inventory"

if [[ -f "$INVENTORY_FILE" ]]; then
  warn "Inventory already exists at ${INVENTORY_FILE} — skipping write."
  info "Delete it and re-run to regenerate."
else

{
  echo "# Ansible inventory — generated by ansibleme.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Host: $(hostname)  Site: ${SITE_CODE}"
  echo

  echo "[ansiblehosts]"
  # EXAANSCLD001 lives at 192.168.69.9 on the CLD LAN.
  # Falls back to hostname -I if the site has no DC entry.
  THIS_MGMT_IP="${SITE_DC[$SITE_CODE]:-$(hostname -I | awk '{print $1}')}"
  printf "%-15s # %s\n" "${THIS_MGMT_IP}" "$(hostname)"
  echo

  echo "[pvenodes]"
  for node in "${PVE_NODES[@]}"; do
    if [[ "$node" == *"#"* ]]; then
      ip_part="${node%%#*}"
      comment_part="# ${node#*# }"
      printf "%-15s %s\n" "${ip_part%% }" "${comment_part}"
    else
      printf "%-15s\n" "$node"
    fi
  done
  echo

  for grp in $(echo "${!DISC_HOSTS_BY_GROUP[@]}" | tr ' ' '\n' | sort); do
    [[ "$grp" == "unknowns" ]] && continue
    [[ -z "${DISC_HOSTS_BY_GROUP[$grp]}" ]] && continue
    echo "[${grp}]"
    echo -n "${DISC_HOSTS_BY_GROUP[$grp]}"
    echo
  done

  if [[ -n "${DISC_HOSTS_BY_GROUP[unknowns]:-}" || -n "$DISC_UNKNOWNS" ]]; then
    echo "# ── Unclassified hosts ────────────────────────────────────────────"
    echo "# These hosts responded but could not be automatically classified."
    echo "# Uncomment and move to the correct group, or investigate manually."
    echo "#"
    echo "# [unknowns]"
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      echo "# ${line}"
    done <<< "${DISC_HOSTS_BY_GROUP[unknowns]:-}${DISC_UNKNOWNS}"
    echo
  fi

  # Convenience meta-group: everything we manage
  echo "[managed:children]"
  [[ ${#PVE_NODES[@]} -gt 0 ]] && echo "pvenodes"
  for grp in $(echo "${!DISC_HOSTS_BY_GROUP[@]}" | tr ' ' '\n' | sort); do
    [[ "$grp" == "unknowns" ]] && continue
    [[ -z "${DISC_HOSTS_BY_GROUP[$grp]}" ]] && continue
    echo "$grp"
  done
  echo

  # linux:children — ensures group_vars/linux/ applies to all Linux hosts.
  # Windows hosts are NOT in this group and therefore do not get become=true.
  echo "[linux:children]"
  echo "managed"
  echo "rudder_servers"
  echo "rudder_relays"
  echo "ansiblehosts"

} > "$INVENTORY_FILE"

chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$INVENTORY_FILE"
success "Inventory written to ${INVENTORY_FILE}"

fi  # end [[ ! -f "$INVENTORY_FILE" ]]

# ------------------------------------------------------------------------------
# 10b. Final pass: clear stale known_hosts for the actual written inventory
# ------------------------------------------------------------------------------
section "10b. Clearing stale SSH host keys for managed IPs"

ANSIBLE_KNOWN_HOSTS="${ANSIBLE_HOME}/.ssh/known_hosts"
mkdir -p "${ANSIBLE_HOME}/.ssh"
touch "$ANSIBLE_KNOWN_HOSTS"
chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "$ANSIBLE_KNOWN_HOSTS"
chmod 644 "$ANSIBLE_KNOWN_HOSTS"

mapfile -t MANAGED_IPS < <(
  grep -hE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' "${CONFIGS_DIR}/inventory/"*.ini 2>/dev/null \
    | awk '{print $1}' | sort -u
)

if [[ ${#MANAGED_IPS[@]} -eq 0 ]]; then
  info "No IPs found in inventory yet — nothing to clear."
else
  CLEARED=0
  for ip in "${MANAGED_IPS[@]}"; do
    if ssh-keygen -R "$ip" -f "$ANSIBLE_KNOWN_HOSTS" &>/dev/null; then
      (( CLEARED++ )) || true
    fi
    if [[ -f /etc/ssh/ssh_known_hosts ]]; then
      ssh-keygen -R "$ip" -f /etc/ssh/ssh_known_hosts &>/dev/null || true
    fi
  done
  success "Checked ${#MANAGED_IPS[@]} managed IP(s); cleared any stale host key entries."
  info "accept-new will silently trust each host's current key on first connect."
fi

# ------------------------------------------------------------------------------
# 11. group_vars scaffolding
# ------------------------------------------------------------------------------
section "11. group_vars scaffolding"

# ── all — vars that apply to every managed host (NO become here) ──────────────
if [[ -f "${ANSIBLE_DIR}/group_vars/all/main.yml" ]]; then
  warn "group_vars/all/main.yml already exists — skipping write."
else
cat > "${ANSIBLE_DIR}/group_vars/all/main.yml" <<EOF
---
# group_vars/all/main.yml
# Generated by ansibleme.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# NOTE: ansible_become is intentionally absent here.
# Linux hosts get become via group_vars/linux/main.yml.
# Windows hosts must never have become=true (no sudo on Windows).
# This was battle-tested on 2026-06-27 — do not add become back here.

ansible_user: ${ANSIBLE_USER}

# Common packages deployed to every Linux host
common_packages:
  - curl
  - dnsutils
  - net-tools
  - nmap
  - tree
  - vim
  - wget
  - grc
  - zsh
  - yamllint
EOF
fi  # end group_vars/all/main.yml

# ── linux — become settings for all Linux hosts ───────────────────────────────
if [[ -f "${ANSIBLE_DIR}/group_vars/linux/main.yml" ]]; then
  warn "group_vars/linux/main.yml already exists — skipping write."
else
cat > "${ANSIBLE_DIR}/group_vars/linux/main.yml" <<EOF
---
# group_vars/linux/main.yml
# Generated by ansibleme.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Privilege escalation for all Linux hosts.
# Applied via [linux:children] in configs/inventory/main.ini which covers:
#   managed (pvenodes, dcs, firewalls), rudder_servers, rudder_relays, ansiblehosts
#
# Windows hosts are NOT in the linux group and must never inherit these settings.
ansible_become:        true
ansible_become_method: sudo
ansible_become_user:   root
EOF
fi  # end group_vars/linux/main.yml

# ── pvenodes — PVE-specific vars ──────────────────────────────────────────────
if [[ -f "${ANSIBLE_DIR}/group_vars/pvenodes/main.yml" ]]; then
  warn "group_vars/pvenodes/main.yml already exists — skipping write."
else
cat > "${ANSIBLE_DIR}/group_vars/pvenodes/main.yml" <<EOF
---
# group_vars/pvenodes/main.yml
# Generated by ansibleme.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

pve_packages:
  - libguestfs-tools
  - python3-proxmoxer
  - python3-requests
  - python3-virtualenv
  - sudo

# Cloud image template IDs (update after first run)
template_ubuntu_noble:  1000
template_debian_trixie: 1001

# Default storage pool for new VMs
pve_default_storage: local-lvm
EOF
fi  # end group_vars/pvenodes/main.yml

chown -R "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_DIR}/group_vars"
success "group_vars scaffolding written."

# ------------------------------------------------------------------------------
# 12. Repo status
# ------------------------------------------------------------------------------
section "12. Playbooks — repo status"

echo
if [[ -L "${ANSIBLE_DIR}" && -d "${ANSIBLE_DIR}" ]]; then
  echo -e "${GREEN}  ✔  /home/ansible/ansible -> ${REPO_DIR}/ansible${NC}"
  echo -e "${GREEN}     Playbooks are available at ${PLAYBOOKS_DIR}${NC}"
else
  echo -e "${YELLOW}  ╔═══════════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${YELLOW}  ║   WARNING — ${ANSIBLE_DIR} is not a symlink to the repo     ║${NC}"
  echo -e "${YELLOW}  ╚═══════════════════════════════════════════════════════════════════╝${NC}"
  echo -e "${YELLOW}  Section 5 should have cloned ${REPO_URL}${NC}"
  echo -e "${YELLOW}  and symlinked ${REPO_DIR}/ansible -> ${ANSIBLE_DIR}${NC}"
  echo -e "${YELLOW}  Check the Section 5 output above for errors.${NC}"
fi
echo
echo -e "${CYAN}  NOTE: configs/inventory and group_vars/ are managed by this script${NC}"
echo -e "${CYAN}  and are NOT part of the repo. Do not overwrite them from git.${NC}"
echo
echo -e "${CYAN}  The exa_pretty callback was downloaded to:${NC}"
echo -e "${GREEN}  ${CALLBACK_DIR}/exa_pretty.py${NC}"
echo -e "${CYAN}  If it failed, re-run: wget -O ${CALLBACK_DIR}/exa_pretty.py ${EXA_PRETTY_URL}${NC}"
echo

# ------------------------------------------------------------------------------
# 13. Connectivity test (optional)
# ------------------------------------------------------------------------------
section "13. Connectivity test"

RUN_PING="n"
if [[ ${#PVE_NODES[@]} -gt 0 ]]; then
  echo -e "${CYAN}  PVE nodes have been configured in the inventory.${NC}"
  echo -e "${CYAN}  The ansible user should already exist on each node (created by the PXE installer).${NC}"
  echo
  read -rp "  Run SSH connectivity test to PVE nodes now? [y/N] " RUN_PING
fi

if [[ "${RUN_PING,,}" == "y" ]]; then
  echo
  echo -e "${CYAN}  Testing SSH connectivity (ansible ping) to [pvenodes]...${NC}"
  echo -e "${CYAN}  Hosts not yet fully onboarded may show UNREACHABLE — that's expected.${NC}"
  echo

  PING_OUT=$(sudo -u "$ANSIBLE_USER" \
    ansible pvenodes -i "${CONFIGS_DIR}/inventory" -m ping 2>&1 || true)

  echo "$PING_OUT"
  echo

  UNREACHABLE=$(echo "$PING_OUT" | grep -c "UNREACHABLE" || true)
  FAILED=$(echo "$PING_OUT" | grep -c "FAILED" || true)
  SUCCESS_COUNT=$(echo "$PING_OUT" | grep -c "pong" || true)

  if [[ $SUCCESS_COUNT -gt 0 ]]; then
    success "${SUCCESS_COUNT} node(s) responded to ping."
  fi
  if [[ $UNREACHABLE -gt 0 || $FAILED -gt 0 ]]; then
    warn "${UNREACHABLE} unreachable / ${FAILED} failed."
    warn "Run pve_onboard.yml as root to complete setup:"
    warn "  ansible-playbook ${PLAYBOOKS_DIR}/proxmox/pve_onboard.yml -i ${CONFIGS_DIR}/inventory --user=root -k"
  fi
else
  info "Skipping connectivity test."
  if [[ ${#PVE_NODES[@]} -gt 0 ]]; then
    info "Run manually any time: ansible pvenodes -i ${CONFIGS_DIR}/inventory -m ping"
  fi
fi

# ------------------------------------------------------------------------------
# 14. Dynamic MOTD
# ------------------------------------------------------------------------------
section "14. Dynamic MOTD"

CITY="${SITE_DISPLAY_CITY:-${SITE_CODE}}"
COUNTRY="${SITE_DISPLAY_COUNTRY:-Unknown}"
ENTITY="${SITE_DISPLAY_ENTITY:-Example Music}"

cat > /etc/update-motd.d/10-examplemusic <<MOTD
#!/usr/bin/env bash
WH='\033[1;37m'; YL='\033[1;33m'; GR='\033[0;32m'; CY='\033[0;36m'; NC='\033[0m'
UPTIME=\$(uptime -p)
LOAD=\$(cut -d' ' -f1-3 /proc/loadavg)
MEM_TOTAL=\$(awk '/MemTotal/{print int(\$2/1024)}' /proc/meminfo)
MEM_FREE=\$(awk '/MemAvailable/{print int(\$2/1024)}' /proc/meminfo)
MEM_USED=\$(( MEM_TOTAL - MEM_FREE ))
DISK=\$(df -h / | awk 'NR==2{print \$3" used of "\$2" ("\$5")"}')
ANSIBLE_VER=\$(ansible --version 2>/dev/null | head -1 || echo "not found")
INV_HOSTS=\$(ansible all -i ${CONFIGS_DIR}/inventory --list-hosts 2>/dev/null | tail -n +2 | wc -l || echo "?")
echo -e "
\${WH}╔══════════════════════════════════════════════════════════════╗\${NC}
\${WH}║     EXAMPLE MUSIC LIMITED: \$(printf '%-35s' "\${HOSTNAME}")║\${NC}
\${WH}╚══════════════════════════════════════════════════════════════╝\${NC}

  \${YL}Site     :\${NC} ${SITE_CODE}: ${CITY}, ${COUNTRY}
  \${YL}Entity   :\${NC} ${ENTITY}
  \${YL}Role     :\${NC} Ansible management node

  \${WH}── Ansible ───────────────────────────────────────────────────\${NC}
    \${CY}Version\${NC}  : \${GR}\${ANSIBLE_VER}\${NC}
    \${CY}Inventory\${NC}: \${GR}${CONFIGS_DIR}/inventory\${NC}
    \${CY}Hosts\${NC}    : \${GR}\${INV_HOSTS} managed host(s)\${NC}

  \${WH}── System ────────────────────────────────────────────────────\${NC}
    \${CY}Uptime\${NC}   : \${GR}\${UPTIME}\${NC}
    \${CY}Load\${NC}     : \${GR}\${LOAD}\${NC}
    \${CY}Memory\${NC}   : \${GR}\${MEM_USED}MB\${NC} used of \${MEM_TOTAL}MB
    \${CY}Disk /\${NC}   : \${GR}\${DISK}\${NC}

  \${WH}── Quick reference ───────────────────────────────────────────\${NC}
    \${CY}Onboard PVE :\${NC} ansible-playbook ${PLAYBOOKS_DIR}/proxmox/pve_onboard.yml -i ${CONFIGS_DIR}/inventory --user=root -k
    \${CY}Ping all    :\${NC} ansible all -i ${CONFIGS_DIR}/inventory -m ping
    \${CY}Templates   :\${NC} ansible-playbook ${PLAYBOOKS_DIR}/proxmox/cloud_templates.yml
"
MOTD

chmod +x /etc/update-motd.d/10-examplemusic

if grep -q "^PrintMotd" /etc/ssh/sshd_config 2>/dev/null; then
  sed -i "s/^PrintMotd.*/PrintMotd yes/" /etc/ssh/sshd_config
else
  echo "PrintMotd yes" >> /etc/ssh/sshd_config
fi

cat > /etc/profile.d/motd.sh <<'EOF'
[[ -x /etc/update-motd.d/10-examplemusic ]] && /etc/update-motd.d/10-examplemusic
EOF

systemctl restart ssh 2>/dev/null || true
success "Dynamic MOTD configured."

# ------------------------------------------------------------------------------
# 15. Sentinel file
# ------------------------------------------------------------------------------
mkdir -p /etc/example-music
jq -n \
  --arg hostname       "$(hostname -s)" \
  --arg role           "ansible" \
  --arg site           "${SITE_CODE}" \
  --arg city           "${SITE_DISPLAY_CITY}" \
  --arg country        "${SITE_DISPLAY_COUNTRY}" \
  --arg entity         "${SITE_DISPLAY_ENTITY}" \
  --arg bootstrapped_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg bootstrapped_by "ansibleme.sh" \
  --arg environment    "${ENV_LONG}" \
  --arg ansible_dir    "${ANSIBLE_DIR}" \
  --arg inventory      "${CONFIGS_DIR}/inventory" \
  --arg ssh_key        "${KEY_FILE}" \
  --argjson pve_nodes  "$(printf '%s\n' "${PVE_NODES[@]:-}" | jq -R . | jq -s .)" \
  '{
    hostname:        $hostname,
    role:            $role,
    site:            $site,
    city:            $city,
    country:         $country,
    entity:          $entity,
    ansible_managed: false,
    bootstrapped_at: $bootstrapped_at,
    bootstrapped_by: $bootstrapped_by,
    environment:     $environment,
    ansible_dir:     $ansible_dir,
    inventory:       $inventory,
    ssh_key:         $ssh_key,
    pve_nodes:       $pve_nodes
  }' > "$NODEINFO"
chmod 0444 "$NODEINFO"
success "Node info written to ${NODEINFO}"

# ------------------------------------------------------------------------------
# 16. Final banner
# ------------------------------------------------------------------------------
echo
echo -e "${GREEN}============================================================${NC}"
echo -e "${GREEN}  SETUP COMPLETE — $(hostname)${NC}"
echo -e "${GREEN}============================================================${NC}"
echo -e "${CYAN}  Site          : ${SITE_CODE} — ${SITE_DISPLAY_CITY}, ${SITE_DISPLAY_COUNTRY}${NC}"
echo -e "${CYAN}  Ansible dir   : ${ANSIBLE_DIR}${NC}"
echo -e "${CYAN}  Inventory     : ${CONFIGS_DIR}/inventory${NC}"
echo -e "${CYAN}  SSH key       : ${KEY_FILE}${NC}"
echo -e "${CYAN}  ansible.cfg   : ${ANSIBLE_CFG}${NC}"
echo -e "${CYAN}  exa_pretty    : ${CALLBACK_DIR}/exa_pretty.py${NC}"
echo

if [[ ! -f "$KEY_FILE" ]]; then
  echo -e "${YELLOW}  +==================================================================+${NC}"
  echo -e "${YELLOW}  |  REMINDER — PRIVATE KEY NOT YET PLACED ON THIS HOST              |${NC}"
  echo -e "${YELLOW}  +==================================================================+${NC}"
  echo -e "${YELLOW}  |${NC}  No ansible-playbook or ad-hoc run will succeed until the"
  echo -e "${YELLOW}  |${NC}  matching private key is copied to:"
  echo -e "${YELLOW}  |${NC}"
  echo -e "${YELLOW}  |${NC}    ${WHITE}${KEY_FILE}${NC}  ${YELLOW}(chown ${ANSIBLE_USER}:${ANSIBLE_USER}, chmod 600)${NC}"
  echo -e "${YELLOW}  +==================================================================+${NC}"
  echo
fi

echo -e "${YELLOW}  ╔═══════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${YELLOW}  ║   NEXT STEPS                                                      ║${NC}"
echo -e "${YELLOW}  ╚═══════════════════════════════════════════════════════════════════╝${NC}"
echo
echo -e "${CYAN}  1. Verify the repo clone and symlink:${NC}"
echo -e "${GREEN}     ls -la ${ANSIBLE_HOME}/example-music-infra${NC}"
echo -e "${GREEN}     ls -la ${ANSIBLE_DIR}${NC}"
echo -e "${CYAN}     To pull the latest changes:${NC}"
echo -e "${GREEN}     git -C ${ANSIBLE_HOME}/example-music-infra pull --ff-only${NC}"
echo
echo -e "${CYAN}  2. Onboard PVE nodes:${NC}"
echo -e "${GREEN}     ansible-playbook ${PLAYBOOKS_DIR}/proxmox/pve_onboard.yml -i ${CONFIGS_DIR}/inventory --user=root -k${NC}"
echo
echo -e "${CYAN}  3. Verify connectivity:${NC}"
echo -e "${GREEN}     ansible all -i ${CONFIGS_DIR}/inventory -m ping${NC}"
echo

if [[ ${#PVE_NODES[@]} -gt 0 ]]; then
  echo -e "${CYAN}  PVE nodes configured (${#PVE_NODES[@]} entries — comment out any not physically present):${NC}"
  i=0
  for node in "${PVE_NODES[@]}"; do
    short="${node%% (*}"
    printf "    %-26s" "$short"
    (( i++ ))
    (( i % 3 == 0 )) && echo
  done
  (( i % 3 != 0 )) && echo
  echo
fi

echo -e "${YELLOW}  Public key (distribute to any host not yet onboarded):${NC}"
echo -e "${GREEN}  $(cat "$KEY_PUB" 2>/dev/null || echo '(not yet generated)')${NC}"
echo
echo -e "${GREEN}============================================================${NC}"
echo
