#!/usr/bin/env python3

# ==================================================================================================
# Example Music Inventory Generator
#
# Authoritative sources: /etc/example-music/sites.csv, /etc/example-music/devices.csv
#
# Requires an apt -y install python3-ipy to be run on your ansible node.
#
# Address allocation policy:
#
#   .1          RTR   Upstream router
#   .2-.4       BMC   iDRAC / iLO / Redfish
#   .5-.7       PVE   Proxmox nodes
#   .10         DCS1  Primary Domain Controller
#   .11         DCS2  Secondary Domain Controller
#   .15         PRV   Provisioning Server
#   .48         SBC   VoIP Session Border Controller
#   .100-.249   DHCP  DHCP Pool
#   .250-.252   SWI   Switches
#   .253        FWL1  Firewall
#   .254        FWL2  Firewall
#
# Everything else for a site — the long tail of real, non-standard devices (extra workstations,
# a Rudder server, a PBX, a NAS, right down to the vending machine — see devices.csv) — comes from
# devices.csv, joined in per-site on the Site column (sites.csv is the "left" table: one row per
# site drives which .ini gets written; devices.csv is the "right" table: zero or more rows per
# site, matched on Site, added into that site's .ini).
#
# Host naming:
#
#   EXA<ROLE><SITE><NNN>
# ==================================================================================================
# Changelog:
#  2026-07-05  Fixed offset_ip() — IPy's IP.__add__ is reserved for merging two adjacent IP()/net
#              objects into a parent CIDR block (see https://pypi.org/project/IPy/), not address
#              offsetting. base + offset with offset as a plain int made IPy's __add__ try to read
#              offset._ipversion, causing 'int' object has no attribute '_ipversion'. Fixed by
#              converting to the integer form with .int(), adding there, then rebuilding an IP from
#              the result.
#  2026-07-05  Rewrote build_ini() to use the standard header block & proper multi-group INI syntax
#              (firewalls/windows_server/windows_desktop/windows_laptop/windows:children), matching
#              windows_bootstrap/inventory/cld.ini's structure. Hostnames (FWL/DCS1/DCS2/WKS1/LAP1)
#              now come from build_hostname() instead of duplicated as inline EXA{ROLE}{SITE}001
#              string literals — known source of truth for EXA<ROLE><SITE><NNN> naming convention.
#  2026-07-05  Wire in unused hostname_map (BMC/PVE) built in generate() into build_ini(). PVE nodes
#              get a real, uncommented [pvenodes] group (matching the existing group_vars/pvenodes/
#              directory) since they're genuinely Ansible-managed. BMC hosts (iDRAC/iLO/Redfish) are
#              not Ansible-managed, so added as commented reference lines only, no group header.
#  2026-07-05  register_ip() now skips "N/A" entirely instead of treating it as a real address. Two
#              unrelated sites both legitimately having "N/A" for Gateway/DC/FW (e.g. VRK, BRD) were
#              colliding with each other on the literal string "N/A". N/A is an established sentinel
#              elsewhere in this estate (ad_schema.yml rejectattr('Subnet', 'equalto', 'N/A')); this
#              brings register_ip() in line with that convention.
#  2026-07-07  Fixed two bugs that made this script unrunnable: a stray "." after
#              ROLE_OFFSETS["FWL"]'s value (hard SyntaxError, the script could not even be
#              imported), and OFFSETS_SINGLE["DCS"] in generate() — OFFSETS_SINGLE never had a
#              "DCS" key (DCS lives in ROLE_OFFSETS, since it's a two-instance role like BMC/FWL/PVE,
#              not a single-instance one like RTR/PRV/SBC/WKS/LAP) — that would have raised
#              KeyError: 'DCS' on the very first site as soon as the syntax error was fixed.
#  2026-07-07  Merged inventory_devices.py's functionality in — this script now reads devices.csv
#              directly (no separate devices_old.csv/devices_new.csv preprocessing pass) and joins
#              each site's device rows into that site's generated .ini. Standard-offset devices
#              (already covered by the address policy above — e.g. a WKS row sitting exactly at
#              .101) and RAC/PVE rows (per longstanding operator instruction: RAC is being
#              decommissioned in favour of BMC, and real PVE nodes are handled by the standard
#              template + group_vars/pvenodes, not the devices.csv exception path) are still
#              excluded, same as inventory_devices.py did. inventory_devices.py is removed —
#              its logic lives here now, applied at generation time instead of as a one-off
#              preprocessing script, so there's one source of truth instead of two files that can
#              drift (devices.csv used to need a separate devices_new.csv regenerated by hand).
#  2026-07-07  Extracted OFFSETS_SINGLE/ROLE_OFFSETS into address_policy.json (sibling to
#              sites.csv) instead of hardcoding them here — bind9-dns.yml's Play 2 needs the same
#              standard-slot address policy (to synthesise DNS records for the standard devices,
#              now that devices.csv is exceptions-only rather than a complete device list) and
#              would otherwise be a second hand-maintained copy that could drift from this one.
#  2026-07-07  Added --emit-devices-json (compute_standard_devices_for_site/emit_devices_for_dns)
#              — bind9-dns.yml consumes this directly instead of re-deriving the standard-slot +
#              devices.csv-exception merge in Jinja, so DNS and the .ini generator can never
#              disagree about which devices are real or what they're called. Only synthesizes
#              slots build_ini() shows uncommented (RTR/PRV/SBC, both FWL instances, first
#              DCS/PVE instance only) — synthesizing the "example" WKS/LAP slots or BMC/DCS2/PVE2/
#              PVE3 caused real hostname collisions with devices.csv's own numbering in testing
#              (e.g. FAL's real WKS Number=1 at octet .100 colliding with the WKS "example" slot's
#              assumed index 1). BRD (legacy alias for BER, identical subnet) is folded into BER
#              entirely, hostnames rebuilt under BER. VRK (provisioning network, manually-assigned
#              roles) never gets standard-slot synthesis, only its real devices.csv rows.
# ==================================================================================================

import csv
import json
import sys
import re
import argparse
from pathlib import Path
from IPy import IP

# ==================================================================================================
# ANSI colours
# ==================================================================================================
C = {
  "red": "\033[31m",
  "green": "\033[32m",
  "yellow": "\033[33m",
  "white": "\033[37m",
  "end": "\033[0m",
}

def msg(col, text):
  print(C[col] + text + C["end"])

# ==================================================================================================
# Address Policy
# ==================================================================================================
# Loaded at runtime from address_policy.json (sibling to sites.csv by default) — this is the
# single source of truth shared with bind9-dns.yml (Play 2 synthesises the same standard-slot
# devices for DNS, independently, from the same file). Do not hardcode a second copy here; if
# these dicts are empty, load_address_policy() hasn't run yet (see main()).
OFFSETS_SINGLE = {}
ROLE_OFFSETS = {}
STANDARD_OFFSETS = {}

def load_address_policy(policy_path: Path):
  global OFFSETS_SINGLE, ROLE_OFFSETS
  if not policy_path.exists():
    raise ValueError(
      f"address_policy.json not found at {policy_path} — this is the shared source of truth "
      f"for the standard address policy (also used by bind9-dns.yml); it must exist alongside "
      f"sites.csv."
    )
  data = json.loads(policy_path.read_text())
  OFFSETS_SINGLE = data["offsets_single"]
  ROLE_OFFSETS = data["role_offsets"]

  # STANDARD_OFFSETS: derived from the address policy just loaded (not a second, separately-
  # maintained copy — inventory_devices.py used to keep its own STANDARD_SINGLE/STANDARD_MULTI
  # tables, which could silently drift from OFFSETS_SINGLE/ROLE_OFFSETS; this builds them from
  # the same source instead). A devices.csv row whose Type+HostOctet exactly matches one of these
  # is already rendered by the standard template for that site — skip it rather than duplicate it.
  STANDARD_OFFSETS.clear()
  for role, offset in OFFSETS_SINGLE.items():
    STANDARD_OFFSETS.setdefault(role, set()).add(offset)
  for role, offsets in ROLE_OFFSETS.items():
    STANDARD_OFFSETS.setdefault(role, set()).update(offsets)

# ==================================================================================================
# devices.csv join — classification of "extra" per-site devices
# ==================================================================================================
# devices.csv columns: Site, Type, Number, HostOctet, OS, ConnectionType, Managed, Notes

# Excluded unconditionally, regardless of octet (per longstanding operator instruction — RAC is
# being decommissioned in favour of BMC; real PVE nodes are handled by the standard template +
# group_vars/pvenodes/, not by the devices.csv exception path).
ALWAYS_EXCLUDE_TYPES = {"RAC", "PVE"}

# Known Type -> existing inventory group, for devices.csv rows that ARE Ansible-managed. Anything
# manageable but not in this map (e.g. a one-off NAS or Rudder relay) falls into a generic
# per-site [site_devices] group instead of a made-up group nothing else references.
DEVICE_GROUP_MAP = {
  "WKS": "windows_desktop",
  "LAP": "windows_laptop",
  "SVR": "windows_server",
  "DCS": "windows_server",
  "FWL": "firewalls",
}

# Manageability default when devices.csv's own Managed column is blank (true for every row at the
# time this was written — nobody has gone through and filled it in yet). Managed=yes/no on a row
# always overrides this; this is only the fallback guess. A real, recognisable server OS is a
# reasonable signal that this is something we'd actually run Ansible against; an appliance OS
# (or no OS at all — a switch, a coffee machine, a payment terminal) is not.
MANAGEABLE_OS_PATTERN = re.compile(
  r"windows|debian|ubuntu|trixie|bookworm|bullseye|noble|red ?hat|rhel|centos|rocky|almalinux",
  re.IGNORECASE,
)

DEVICE_REQUIRED_COLUMNS = [
  "Site", "Type", "Number", "HostOctet", "OS", "ConnectionType", "Managed", "Notes"
]

# ==================================================================================================
# Special Sites
# ==================================================================================================

SPECIAL_SITES = {
  "VRK": "Virtual Rack / Cloud Abstraction Site (192.168.139.0/24)",
  "CLD": "Cloud Aggregation Site (192.168.69.0/24)",
}

# ==================================================================================================
# Collision Rules
# ==================================================================================================

## These roles are allowed to share same IP
ALLOWED_IP_ALIASES = {
  ("Gateway", "Firewall"),
  ("Firewall", "Gateway"),
}

## BRD / BER are allowed to overlap (legacy vs modern naming)
## Mohrenstraße 37 10117, Berlin, 18:53 CET, Donnerstag 9th November 1989
ALLOWED_SITE_OVERLAP = {
  ("BRD", "BER"),
  ("BER", "BRD"),
}

# ==================================================================================================
# State
# ==================================================================================================

seen_subnets = {}
seen_ips = {}

# ==================================================================================================
# Helpers
# ==================================================================================================
def validate_cidr(subnet: str):
  subnet = str(subnet).strip().replace("\r", "").replace("\n", "").replace(" ", "")

  try:
    net = IP(str(subnet))   # <-- FIX HERE
  except Exception as e:
    raise ValueError(f"Invalid CIDR '{subnet}': {e}")

  if net.version() != 4:
    raise ValueError(f"IPv4 only supported: {subnet}")
  return net

def offset_ip(net: IP, offset: int) -> str:
  base = IP(net.strNormal(0).split('/')[0])

  # IPy's IP + IP merges adjacent CIDR blocks into a parent network — it is not address offsetting,
  # and fails with a confusing AttributeError if the right-hand side isn't also an IP object. Do the
  # arithmetic on the integer form instead, then rebuild an IP from the result.
  return str(IP(base.int() + offset))

def register_subnet(site: str, net: IP):
  net = IP(str(net))  # FORCE canonical IP object

  for existing_net, existing_site in seen_subnets.items():
    existing_net = IP(str(existing_net))  # FORCE same type

    if (site, existing_site) in ALLOWED_SITE_OVERLAP:
      continue
    if net.overlaps(existing_net):
      raise ValueError(
        f"\nCIDR overlap detected:\n"
        f"  {site} ({net})\n"
        f"  conflicts with {existing_site} ({existing_net})"
      )
  seen_subnets[net.strNormal()] = site

def register_ip(site: str, ip: str, role: str):
  # "N/A" is an established sentinel for "no real value" elsewhere in this estate (e.g. ad_schema.yml
  # rejectattr('Subnet', 'equalto', 'N/A')). It's NOT a real address & must never be collision-checked
  # — two unrelated sites both legitimately having "N/A" for a field is not a collision.
  if str(ip).strip().upper() in ("N/A", "NA", ""):
    return

  if ip in seen_ips:
    prev_site, prev_role = seen_ips[ip]

    # allow intentional role sharing
    if (role, prev_role) in ALLOWED_IP_ALIASES:
      return

    # allow BRD/BER coexistence
    if (site, prev_site) in ALLOWED_SITE_OVERLAP:
      return

    raise ValueError(
      f"\nIP collision detected:\n"
      f"  {ip}\n"
      f"  {site} ({role})\n"
      f"  already used by {prev_site} ({prev_role})"
    )
  seen_ips[ip] = (site, role)

def build_hostname(role: str, site: str, index: int) -> str:
  return f"EXA{role}{site}{index:03d}"

# ==================================================================================================
# devices.csv — load, classify, and join per site
# ==================================================================================================

def validate_devices_csv_structure(rows):
  if not rows:
    return
  header = rows[0].keys()
  for col in DEVICE_REQUIRED_COLUMNS:
    if col not in header:
      raise ValueError(f"devices.csv missing column: {col}")

def is_managed(row: dict) -> bool:
  """Managed column wins if the operator has set it; otherwise guess from OS."""
  flag = row.get("Managed", "").strip().lower()
  if flag in ("yes", "y", "true", "1"):
    return True
  if flag in ("no", "n", "false", "0"):
    return False
  return bool(MANAGEABLE_OS_PATTERN.search(row.get("OS", "") or ""))

def needs_review(row: dict) -> bool:
  """Ambiguous rows: no explicit Managed flag AND no OS-based signal either way."""
  flag = row.get("Managed", "").strip().lower()
  if flag in ("yes", "y", "true", "1", "no", "n", "false", "0"):
    return False
  return not (row.get("OS", "") or "").strip()

def load_devices(devices_path: Path):
  """
  Reads devices.csv and returns (devices_by_site, stats) where devices_by_site maps
  site -> list of processed extra-host dicts (hostname, ip, group, managed, notes, type),
  ready to hand to build_ini(). Applies the same exclusions inventory_devices.py used to
  apply as a separate preprocessing pass (standard-offset rows, RAC/PVE rows).
  """
  stats = {
    "total": 0, "excluded_standard": 0, "excluded_always": 0,
    "included_managed": 0, "included_reference": 0, "needs_review": 0,
  }
  devices_by_site = {}

  if not devices_path.exists():
    msg("yellow", f"devices.csv not found at {devices_path} — generating standard template only.")
    return devices_by_site, stats

  rows = list(csv.DictReader(devices_path.open()))
  validate_devices_csv_structure(rows)
  stats["total"] = len(rows)

  for r in rows:
    site = r["Site"].strip()
    dtype = r["Type"].strip().upper()
    octet_raw = r["HostOctet"].strip()

    if dtype in ALWAYS_EXCLUDE_TYPES:
      stats["excluded_always"] += 1
      continue

    octet = int(octet_raw) if octet_raw.isdigit() else None
    if octet is not None and octet in STANDARD_OFFSETS.get(dtype, set()):
      stats["excluded_standard"] += 1
      continue

    try:
      number = int(r["Number"])
    except (KeyError, ValueError):
      msg("yellow", f"Skipping devices.csv row with non-numeric Number: {r}")
      continue

    managed = is_managed(r)
    review = needs_review(r)
    if review:
      stats["needs_review"] += 1
    if managed:
      stats["included_managed"] += 1
    else:
      stats["included_reference"] += 1

    devices_by_site.setdefault(site, []).append({
      "hostname": build_hostname(dtype, site, number),
      "octet": octet,
      "type": dtype,
      "group": DEVICE_GROUP_MAP.get(dtype, "site_devices"),
      "managed": managed,
      "needs_review": review,
      "os": r.get("OS", ""),
      "notes": r.get("Notes", ""),
    })

  return devices_by_site, stats

def render_device_line(net: IP, dev: dict) -> str:
  note = f"  # {dev['notes']}" if dev["notes"] else ""
  if dev["octet"] is None:
    return f"# {dev['hostname']}  (no HostOctet in devices.csv){note}"
  ip = offset_ip(net, dev["octet"])
  return f"{dev['hostname']}  ansible_host={ip}{note}"

# ==================================================================================================
# Output
# ==================================================================================================

def site_filename(site: str):
  return f"{site.lower()}.ini"


def build_ini(site, row, vals, hostnames, net, site_devices):
  managed_by_group = {}
  reference_lines = []
  review_lines = []

  for dev in site_devices:
    line = render_device_line(net, dev)
    if dev["needs_review"]:
      review_lines.append(f"# NEEDS REVIEW (no OS/Managed set): {line}")
    elif dev["managed"]:
      managed_by_group.setdefault(dev["group"], []).append(line)
    else:
      reference_lines.append(line)

  extra_group_blocks = ""
  for group, lines in managed_by_group.items():
    if group in ("windows_desktop", "windows_laptop", "windows_server", "firewalls"):
      # These groups already exist above with their standard-template entries — append to
      # the SAME group rather than declaring it a second time (INI parsers merge repeated
      # group headers, but keeping it readable matters more than being clever here).
      continue
    extra_group_blocks += f"\n[{group}]\n" + "\n".join(lines) + "\n"

  # Devices destined for windows_desktop/windows_laptop/windows_server/firewalls get folded
  # into those groups' existing blocks below via these lookups.
  def extra_for(group):
    lines = managed_by_group.get(group, [])
    return ("\n" + "\n".join(lines)) if lines else ""

  other_devices_block = ""
  if reference_lines or review_lines:
    other_devices_block = (
      "\n# Other devices from devices.csv — not Ansible-managed (or not yet classified), "
      "for reference only:\n"
      + "\n".join(f"# {l}" for l in reference_lines)
      + ("\n" + "\n".join(review_lines) if review_lines else "")
      + "\n"
    )

  return f"""# ==================================================================================================
# inventory/{site_filename(site)}
# Example Music Limited — {vals['CITY']} ({site})
#
# --------------------------------------------------------------------------------------------------
# THIS FILE IS AUTOMATICALLY GENERATED.
#
# Source:
# /etc/example-music/sites.csv (standard template)
# /etc/example-music/devices.csv (per-site extras, joined in on the Site column)
#
# DO NOT EDIT.
# Changes may be overwritten.
# --------------------------------------------------------------------------------------------------
#
# Addressing
#
# .10 Primary DC
# .11 Secondary DC
# .101 Example workstation
# .102 Example laptop
# .253 Primary Firewall
# .254 Secondary Firewall
#
# ==================================================================================================

[firewalls]
{hostnames['FWL1']}  ansible_host={vals['FW']}  ansible_user=ansible  ansible_connection=ssh
{hostnames['FWL2']}  ansible_host={vals['FW']}  ansible_user=ansible  ansible_connection=ssh{extra_for('firewalls')}

[windows_server]
{hostnames['DCS1']}  ansible_host={vals['DCS1']}
# {hostnames['DCS2']}  ansible_host={vals['DCS2']}{extra_for('windows_server')}

[windows_desktop]
# {hostnames['WKS1']}  ansible_host={vals['WKS1']}{extra_for('windows_desktop')}

[windows_laptop]
# {hostnames['LAP1']}  ansible_host={vals['LAP1']}{extra_for('windows_laptop')}

[pvenodes]
{hostnames['PVE1']}  ansible_host={vals['PVE1']}
# {hostnames['PVE2']}  ansible_host={vals['PVE2']}
# {hostnames['PVE3']}  ansible_host={vals['PVE3']}

[windows:children]
windows_server
windows_desktop
windows_laptop
{extra_group_blocks}
# Out-of-band management (iDRAC/iLO/Redfish) — not Ansible-managed, for
# reference only:
# {hostnames['BMC1']}  {vals['BMC1']}
# {hostnames['BMC2']}  {vals['BMC2']}
# {hostnames['BMC3']}  {vals['BMC3']}
{other_devices_block}"""

# ==================================================================================================
# CSV validation
# ==================================================================================================

REQUIRED_COLUMNS = [
  "Site", "City", "Country", "CountryCode", "Subnet", "Gateway", "DC", "FW", "Landline", "Mobile",
  "Timezone", "AnsibleRegion", "Entity"
]

def validate_csv_structure(rows):
  if not rows:
    raise ValueError("CSV empty")
  header = rows[0].keys()

  for col in REQUIRED_COLUMNS:
    if col not in header:
      raise ValueError(f"Missing column: {col}")

# ==================================================================================================
# Standard device synthesis — for consumers other than the .ini generator (e.g. bind9-dns.yml,
# which needs a DNS record for every confirmed-real standard-slot device now that devices.csv is
# exceptions-only rather than a complete device list — see address_policy.json's header comment)
# ==================================================================================================
# Only slots build_ini() shows UNCOMMENTED (confirmed real, not a "may not be built yet"
# placeholder) are synthesized here:
#   - RTR/PRV/SBC: single-instance infra roles, always physically present at a real site (even
#     though they're not Ansible-managed/not rendered in the .ini at all)
#   - FWL: both instances (FWL1/FWL2) are real in every site's .ini
#   - DCS/PVE: only the FIRST instance is real in the .ini (DCS2/PVE2/PVE3 are commented —
#     "may not be built yet"); synthesizing a DNS record for a DC/PVE node that might not exist
#     would be actively misleading, and WOULD collide with devices.csv's OWN numbering for real
#     extra instances at that site (devices.csv's Number is chosen independently by whoever
#     filled in the row, not guaranteed to skip index 1)
#   - WKS/LAP "example" slots and BMC (all always commented/reference-only in the .ini) are never
#     synthesized here for the same reason — see the Notes above about hostname collisions this
#     caused in testing (e.g. a real devices.csv "WKS Number=1" at a non-standard octet
#     legitimately reusing EXAWKS<SITE>001, the same hostname the "example" placeholder would use)
DNS_SINGLE_ROLES = ["RTR", "PRV", "SBC"]
DNS_MULTI_ALL_INSTANCES = {"FWL"}
DNS_MULTI_FIRST_INSTANCE_ONLY = {"DCS", "PVE"}

def compute_standard_devices_for_site(site: str, net: IP):
  """
  Returns every confirmed-real standard-slot device for one site as a flat list of dicts
  (Site, Hostname, HostOctet, Notes) — the same addresses build_ini() derives for the ones it
  shows uncommented, just shaped for JSON consumption instead of f-string interpolation.
  """
  devices = []
  for role in DNS_SINGLE_ROLES:
    devices.append({
      "Site": site,
      "Hostname": build_hostname(role, site, 1),
      "HostOctet": str(OFFSETS_SINGLE[role]),
      "Notes": f"Standard {role} slot",
    })
  for role, offsets in ROLE_OFFSETS.items():
    if role in DNS_MULTI_ALL_INSTANCES:
      selected = list(enumerate(offsets, start=1))
    elif role in DNS_MULTI_FIRST_INSTANCE_ONLY:
      selected = [(1, offsets[0])]
    else:
      continue  # e.g. BMC — always commented/reference-only, never synthesized for DNS
    for i, offset in selected:
      devices.append({
        "Site": site,
        "Hostname": build_hostname(role, site, i),
        "HostOctet": str(offset),
        "Notes": f"Standard {role} slot {i}",
      })
  return devices

# BRD (West Berlin) is a real, separate site that happens to share BER's exact subnet — see
# ALLOWED_SITE_OVERLAP above, which already treats this as intentional: the .ini generator gives
# BRD its own brd.ini with its own EXA...BRD... hostnames at the same IPs as BER's. Two hostnames
# resolving to the same address is normal DNS (like aliases), so BRD gets its own standard-slot
# synthesis and keeps its own devices.csv rows here too — it is NOT folded into BER. (An earlier
# version of this function did fold BRD into BER, which silently erased BRD's own identity and
# its real devices.csv rows — wrong, caught in review.)

# Sites that have a real sites.csv row/subnet but deliberately do NOT follow the standard
# per-site convention (per bind9-dns.yml's own "CLD BLACK SWAN" documentation for VRK: the
# provisioning network, with manually-assigned roles — no EXADCS, no EXAPVE, no EXASBC). Their
# standard-slot devices are never synthesized; only their real devices.csv rows appear.
NON_STANDARD_SITES = {"VRK"}

def emit_devices_for_dns(csv_path: Path, devices_path: Path):
  """
  Prints the FULL, deduplicated device list (every standard-slot device for every site, plus
  every devices.csv exception that isn't just a redundant description of a standard slot) as
  JSON to stdout, with full_ip already resolved — everything bind9-dns.yml needs to generate DNS
  records, computed by the exact same rules (STANDARD_OFFSETS/ALWAYS_EXCLUDE_TYPES exclusion,
  build_hostname, ALLOWED_SITE_OVERLAP) the .ini generator uses, so the two can never disagree
  about which devices are real or what they're called. BRD/BER's shared subnet duplicates IPs
  under different hostnames by design — bind9-dns.yml keeps BRD out of the per-site *reverse*
  zone loop only (a subnet can only have one authoritative reverse zone; BER owns it), not out of
  the forward zone.
  """
  rows = list(csv.DictReader(csv_path.open()))
  validate_csv_structure(rows)

  subnet_base = {}
  all_devices = []
  for r in rows:
    try:
      net = validate_cidr(r["Subnet"])
    except ValueError:
      continue  # e.g. Subnet == "N/A" — same rows generate()'s per-site loop would also choke on
    subnet_base[r["Site"]] = ".".join(net.strNormal(0).split("/")[0].split(".")[:3])
    if r["Site"] in NON_STANDARD_SITES:
      continue  # e.g. VRK — no standard-convention devices, only its real devices.csv rows
    all_devices.extend(compute_standard_devices_for_site(r["Site"], net))

  devices_by_site, _stats = load_devices(devices_path)
  for site, site_devices in devices_by_site.items():
    for dev in site_devices:
      all_devices.append({
        "Site": site,
        "Hostname": dev["hostname"],
        "HostOctet": str(dev["octet"]) if dev["octet"] is not None else "",
        "Notes": dev["notes"],
      })

  for d in all_devices:
    base = subnet_base.get(d["Site"], "")
    d["full_ip"] = f"{base}.{d['HostOctet']}" if (base and d["HostOctet"]) else ""

  print(json.dumps(all_devices))

# ==================================================================================================
# Generator
# ==================================================================================================

def generate(csv_path: Path, out_dir: Path, devices_path: Path):
  rows = list(csv.DictReader(csv_path.open()))
  validate_csv_structure(rows)

  out_dir.mkdir(parents=True, exist_ok=True)

  devices_by_site, device_stats = load_devices(devices_path)

  for r in rows:
    site = r["Site"]
    net = validate_cidr(r["Subnet"])

    register_subnet(site, net)

    vals = {
      "SITE": site,
      "CITY": r["City"],
      "COUNTRY": r["Country"],
      "SUBNET": r["Subnet"],
      "GATEWAY": r["Gateway"],
      "DC": r["DC"],
      "FW": r["FW"],
      "TZ": r["Timezone"],
      "REGION": r["AnsibleRegion"],
    }

    hostname_map = {}

    ## fixed single-role offsets
    vals["RTR"] = offset_ip(net, OFFSETS_SINGLE["RTR"])
    vals["PRV"] = offset_ip(net, OFFSETS_SINGLE["PRV"])
    vals["SBC"] = offset_ip(net, OFFSETS_SINGLE["SBC"])
    vals["WKS1"] = offset_ip(net, OFFSETS_SINGLE["WKS"])
    vals["LAP1"] = offset_ip(net, OFFSETS_SINGLE["LAP"])

    ## fixed multi-role offsets (BMC/PVE etc)
    for role, offsets in ROLE_OFFSETS.items():
      for i, off in enumerate(offsets, start=1):
        ip = offset_ip(net, off)
        vals[f"{role}{i}"] = ip

        # NEW: deterministic hostname (3-digit safe)
        hostname_map[f"{role}{i}"] = build_hostname(role, site, i)

    # DCS special (DCS is a two-instance role, defined in ROLE_OFFSETS — not OFFSETS_SINGLE)
    vals["DCS1"] = offset_ip(net, ROLE_OFFSETS["DCS"][0])
    vals["DCS2"] = offset_ip(net, ROLE_OFFSETS["DCS"][1])

    # Hostnames for roles that appear in .ini — built via build_hostname() so  EXA<ROLE><SITE><NNN>
    # convention lives in one place rather than being duplicated as inline string literals.
    hostnames = {
      "FWL1": build_hostname("FWL", site, 1),
      "DCS1": build_hostname("DCS", site, 1),
      "DCS2": build_hostname("DCS", site, 2),
      "WKS1": build_hostname("WKS", site, 1),
      "LAP1": build_hostname("LAP", site, 1),
    }
    hostnames.update(hostname_map)

    # register IPs — standard template
    register_ip(site, vals["GATEWAY"], "Gateway")
    register_ip(site, vals["DC"], "Domain Controller")
    register_ip(site, vals["FW"], "Firewall")
    register_ip(site, vals["RTR"], "Router")

    # register IPs — devices.csv extras for this site (real collisions against the standard
    # template, or between two devices.csv rows, are still caught here)
    site_devices = devices_by_site.get(site, [])
    for dev in site_devices:
      if dev["octet"] is not None:
        register_ip(site, offset_ip(net, dev["octet"]), dev["type"])

    dest = out_dir / site_filename(site)

    if dest.exists():
      msg("yellow", f"{dest} exists")
      if input("Overwrite? [y/N]: ").strip().lower() != "y":
        continue

    dest.write_text(build_ini(site, r, vals, hostnames, net, site_devices))
    msg("green", f"Wrote {dest}")

  msg("white",
    f"\ndevices.csv: {device_stats['total']} rows read | "
    f"{device_stats['excluded_standard']} already-standard (skipped) | "
    f"{device_stats['excluded_always']} RAC/PVE (skipped) | "
    f"{device_stats['included_managed']} added as managed hosts | "
    f"{device_stats['included_reference']} added as reference-only | "
    f"{device_stats['needs_review']} flagged NEEDS REVIEW (no OS/Managed set)"
  )

# ==================================================================================================
# CLI
# ==================================================================================================

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("csv", type=Path, help="Path to sites.csv")
  parser.add_argument("-o", "--out", type=Path, default=Path.home() / "ansible/inventory")
  parser.add_argument(
    "--devices", type=Path, default=None,
    help="Path to devices.csv (default: devices.csv next to sites.csv)"
  )
  parser.add_argument(
    "--policy", type=Path, default=None,
    help="Path to address_policy.json (default: address_policy.json next to sites.csv)"
  )
  parser.add_argument(
    "--emit-devices-json", action="store_true",
    help="Print the full merged device list (standard-slot + devices.csv exceptions, full_ip "
         "resolved) as JSON to stdout instead of writing .ini files — used by bind9-dns.yml to "
         "generate DNS records from the exact same data the .ini generator uses."
  )
  args = parser.parse_args()

  devices_path = args.devices if args.devices is not None else args.csv.parent / "devices.csv"
  policy_path = args.policy if args.policy is not None else args.csv.parent / "address_policy.json"

  try:
    load_address_policy(policy_path)
    if args.emit_devices_json:
      emit_devices_for_dns(args.csv, devices_path)
    else:
      generate(args.csv, args.out, devices_path)
  except Exception as e:
    msg("red", f"[FATAL]\n{e}")
    sys.exit(2)

if __name__ == "__main__":
  main()
