# =============================================================================
# inventory/kge.ini
# Example Music Limited — KGE site (Aarhus)
# =============================================================================
# Changelog:
#   2026-06-20  Initial file
# =============================================================================

[firewalls]
EXAFWLKGE001  ansible_host=192.168.139.65  ansible_user=ansible ansible_connection=ssh

[windows_server]
# EXADCSKGE001  ansible_host=192.168.65.10

[windows_desktop]
# EXAWKSKGE001  ansible_host=192.168.65.xxx

[windows_laptop]
# EXALAPKGE001  ansible_host=192.168.65.xxx

[windows:children]
windows_server
windows_desktop
windows_laptop
