# =============================================================================
# salt/pillar/sites.sls
# Example Music Limited — Site -> {city, country, entity} lookup
# =============================================================================
# THIS FILE IS AUTOMATICALLY GENERATED by benarbejde/generate_inventory.py
# --emit-site-grains-pillar. Source: sites.csv (single source of truth) -- do not
# hand-edit, regenerate instead. Consumed by salt/states/grains/init.sls.
# =============================================================================

sites:
  AAR:
    city: "Aarhus"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  ABD:
    city: "Aberdeen"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  AKL:
    city: "Auckland"
    country: "New Zealand"
    entity: "Example Music (New Zealand) Tapui"
  AMS:
    city: "Amsterdam"
    country: "Netherlands"
    entity: "Example Music (Nederland) B.V."
  ATL:
    city: "Atlanta"
    country: "United States"
    entity: "Example Music (US) LLC."
  BER:
    city: "Berlin"
    country: "Germany"
    entity: "Example Music (Deutschland) GmbH"
  BIR:
    city: "Birmingham"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  BON:
    city: "Bonn"
    country: "Germany"
    entity: "Example Music (Deutschland) GmbH"
  BRD:
    city: "West Berlin (legacy alias for BER)"
    country: "Germany"
    entity: "Example Music (Deutschland) GmbH"
  BRK:
    city: "Brockville"
    country: "Canada"
    entity: "Example Music (Canada) Inc."
  BRT:
    city: "Beirut"
    country: "Lebanon"
    entity: "Example Music (Lebanon) SAL"
  CHI:
    city: "Chicago"
    country: "United States"
    entity: "Example Music (US) LLC."
  CLD:
    city: "CloudSite"
    country: "Global"
    entity: "Example Music Limited"
  CLY:
    city: "Clydebank"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  COV:
    city: "Coventry"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  CPH:
    city: "Copenhagen"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  DRS:
    city: "Dresden"
    country: "Germany"
    entity: "Example Music (Deutschland) GmbH"
  DUN:
    city: "Dundee"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  DUS:
    city: "Dusseldorf"
    country: "Germany"
    entity: "Example Music (Deutschland) GmbH"
  EDI:
    city: "Edinburgh"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  FAL:
    city: "Falkirk"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  FAX:
    city: "Faxe"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  FRD:
    city: "Fredericia Havn"
    country: "Denmark"
    entity: "Example Music Limited"
  FRE:
    city: "Fredericia"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  GLA:
    city: "Glasgow"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  GOT:
    city: "Gothenburg"
    country: "Sweden"
    entity: "Example Music (Sverige) AB"
  HAL:
    city: "Halifax"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  HUL:
    city: "Hull"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  KGE:
    city: "Koge"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  KOR:
    city: "Korsor"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  LAX:
    city: "Los Angeles"
    country: "United States"
    entity: "Example Music (US) LLC."
  LIV:
    city: "Liverpool"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  LND:
    city: "London"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  MCR:
    city: "Manchester"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  MEL:
    city: "Melbourne"
    country: "Australia"
    entity: "Example Music (Australia) Pty Ltd"
  MIA:
    city: "Miami"
    country: "United States"
    entity: "Example Music (US) LLC."
  MIL:
    city: "Milan"
    country: "Italy"
    entity: "Example Music (Italia) S.p.a."
  MTL:
    city: "Montreal"
    country: "Canada"
    entity: "Example Music (Canada) Inc."
  MUN:
    city: "Munich"
    country: "Germany"
    entity: "Example Music (Deutschland) GmbH"
  NEW:
    city: "Newcastle"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  NJC:
    city: "New Jersey"
    country: "United States"
    entity: "Example Music (US) LLC."
  NYB:
    city: "Nyborg"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  NYC:
    city: "New York City"
    country: "United States"
    entity: "Example Music (US) LLC."
  ODE:
    city: "Odense"
    country: "Denmark"
    entity: "Example Music (Danmark) ApS"
  OSL:
    city: "Oslo"
    country: "Norway"
    entity: "Example Music (Norge) ASA"
  PER:
    city: "Perth"
    country: "United Kingdom"
    entity: "Example Music (Scotland) Ltd"
  SEA:
    city: "Seattle"
    country: "United States"
    entity: "Example Music (US) LLC."
  SFO:
    city: "San Francisco"
    country: "United States"
    entity: "Example Music (US) LLC."
  SHE:
    city: "Sheffield"
    country: "United Kingdom"
    entity: "Example Music (England) Ltd"
  SYD:
    city: "Sydney"
    country: "Australia"
    entity: "Example Music (Australia) Pty Ltd"
  TOR:
    city: "Toronto"
    country: "Canada"
    entity: "Example Music (Canada) Inc."
  VIE:
    city: "Vienna"
    country: "Austria"
    entity: "Example Music (Osterreich) GmbH"
  VRK:
    city: "VRack"
    country: "Global"
    entity: "Example Music Limited"
