---
# group_vars/pvenodes/main.yml
# Proxmox-specific variables

pve_packages:
  - libguestfs-tools
  - jq
  - python3-proxmoxer
  - python3-requests
  - python3-virtualenv
  - sudo
  - unattended-upgrades

# Cloud image template IDs (update after first run)
template_ubuntu_noble:    1000
template_debian_trixie:   1001

# Default storage pool for new VMs
pve_default_storage: local-lvm
