"use strict";
module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 16,
    fontFamily: '"JetBrainsMono Nerd Font", Menlo, Monaco, "Courier New", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: '#00cc00',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#00cc00',
    backgroundColor: '#002b36',
    selectionColor: 'rgba(255, 255, 255, 1)',
    borderColor: '#073642',
    css: '',
    termCSS: `
      ::selection {
        background: white !important;
        color: black !important;
      }
    `,
    workingDirectory: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#002b36',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#93a1a1',
      lightBlack: '#657b83',
      lightRed: '#cb4b16',
      lightGreen: '#586e75',
      lightYellow: '#839496',
      lightBlue: '#6c71c4',
      lightMagenta: '#d33682',
      lightCyan: '#2aa198',
      lightWhite: '#fdf6e3',
    },
    shell: 'C:\\Program Files\\PowerShell\\7\\pwsh.exe',
    shellArgs: ['-NoLogo'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    webLinksActivationKey: '',
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [
    'hyper-search',
    'hyper-pane',
    'hypercwd',
    'hyper-tabs-enhanced',
    'hyper-rename-tab',
    'hyper-tab-icons-plus',
  ],
  localPlugins: [],
  keymaps: {
    'tab:rename': 'ctrl+shift+r',
    'tab:new': 'ctrl+shift+t',
  },
};
